/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateTaskManagerCommand = {
    /**
     * @type string
    */
    title: string | null;
    /**
     * @type string
    */
    description: string | null;
};