/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ForgetPasswordUserCommand = {
    /**
     * @type string
    */
    token: string | null;
    /**
     * @type string
    */
    newPassword: string | null;
};