/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetApiTaskManagerQueryParams = {
    /**
     * @type integer | undefined, int32
    */
    PageNumber?: number;
    /**
     * @type integer | undefined, int32
    */
    PageSize?: number;
    /**
     * @type string | undefined
    */
    Search?: string;
};

/**
 * @description OK
*/
export type GetApiTaskManager200 = any;

export type GetApiTaskManagerQueryResponse = GetApiTaskManager200;

export type GetApiTaskManagerQuery = {
    Response: GetApiTaskManager200;
    QueryParams: GetApiTaskManagerQueryParams;
    Errors: any;
};