/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetApiAuthVerifyAccountActivationQueryParams = {
    /**
     * @type string
    */
    Code: string;
};

/**
 * @description OK
*/
export type GetApiAuthVerifyAccountActivation200 = any;

export type GetApiAuthVerifyAccountActivationQueryResponse = GetApiAuthVerifyAccountActivation200;

export type GetApiAuthVerifyAccountActivationQuery = {
    Response: GetApiAuthVerifyAccountActivation200;
    QueryParams: GetApiAuthVerifyAccountActivationQueryParams;
    Errors: any;
};