/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description OK
*/
export type GetApiAuthMe200 = any;

export type GetApiAuthMeQueryResponse = GetApiAuthMe200;

export type GetApiAuthMeQuery = {
    Response: GetApiAuthMe200;
    Errors: any;
};