/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetApiAuthVerifyResetPasswordQueryParams = {
    /**
     * @type string
    */
    Token: string;
};

/**
 * @description OK
*/
export type GetApiAuthVerifyResetPassword200 = any;

export type GetApiAuthVerifyResetPasswordQueryResponse = GetApiAuthVerifyResetPassword200;

export type GetApiAuthVerifyResetPasswordQuery = {
    Response: GetApiAuthVerifyResetPassword200;
    QueryParams: GetApiAuthVerifyResetPasswordQueryParams;
    Errors: any;
};