/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Unit } from "./Unit.ts";

export type GetApiTaskManagerIdPathParams = {
    /**
     * @type string, uuid
    */
    Id: string;
};

/**
 * @description OK
*/
export type GetApiTaskManagerId200 = Unit;

export type GetApiTaskManagerIdQueryResponse = GetApiTaskManagerId200;

export type GetApiTaskManagerIdQuery = {
    Response: GetApiTaskManagerId200;
    PathParams: GetApiTaskManagerIdPathParams;
    Errors: any;
};