/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type LoginUserCommand = {
    /**
     * @type string
    */
    email: string | null;
    /**
     * @type string
    */
    password: string | null;
};