/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ForgetPasswordUserCommand } from "./ForgetPasswordUserCommand.ts";
import type { ResponseApiVm } from "./ResponseApiVm.ts";

/**
 * @description OK
*/
export type PostApiAuthResetPassword200 = ResponseApiVm;

export type PostApiAuthResetPasswordMutationRequest = ForgetPasswordUserCommand;

export type PostApiAuthResetPasswordMutationResponse = PostApiAuthResetPassword200;

export type PostApiAuthResetPasswordMutation = {
    Response: PostApiAuthResetPassword200;
    Request: PostApiAuthResetPasswordMutationRequest;
    Errors: any;
};