/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LoginGoogleCommand } from "./LoginGoogleCommand.ts";
import type { UserExtendVmResponseApiVm } from "./UserExtendVmResponseApiVm.ts";

/**
 * @description OK
*/
export type PostApiAuthGoogle200 = UserExtendVmResponseApiVm;

export type PostApiAuthGoogleMutationRequest = LoginGoogleCommand;

export type PostApiAuthGoogleMutationResponse = PostApiAuthGoogle200;

export type PostApiAuthGoogleMutation = {
    Response: PostApiAuthGoogle200;
    Request: PostApiAuthGoogleMutationRequest;
    Errors: any;
};