/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ActivationAccountUserCommand } from "./ActivationAccountUserCommand.ts";
import type { ResponseApiVm } from "./ResponseApiVm.ts";

/**
 * @description OK
*/
export type PostApiAuthAccountActivation200 = ResponseApiVm;

export type PostApiAuthAccountActivationMutationRequest = ActivationAccountUserCommand;

export type PostApiAuthAccountActivationMutationResponse = PostApiAuthAccountActivation200;

export type PostApiAuthAccountActivationMutation = {
    Response: PostApiAuthAccountActivation200;
    Request: PostApiAuthAccountActivationMutationRequest;
    Errors: any;
};