/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RefreshTokenUserCommand } from "./RefreshTokenUserCommand.ts";

/**
 * @description OK
*/
export type PostApiAuthRefresh200 = any;

export type PostApiAuthRefreshMutationRequest = RefreshTokenUserCommand;

export type PostApiAuthRefreshMutationResponse = PostApiAuthRefresh200;

export type PostApiAuthRefreshMutation = {
    Response: PostApiAuthRefresh200;
    Request: PostApiAuthRefreshMutationRequest;
    Errors: any;
};