/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegisterUserCommand } from "./RegisterUserCommand.ts";
import type { UserExtendVmResponseApiVm } from "./UserExtendVmResponseApiVm.ts";

/**
 * @description OK
*/
export type PostApiAuthRegister200 = UserExtendVmResponseApiVm;

export type PostApiAuthRegisterMutationRequest = RegisterUserCommand;

export type PostApiAuthRegisterMutationResponse = PostApiAuthRegister200;

export type PostApiAuthRegisterMutation = {
    Response: PostApiAuthRegister200;
    Request: PostApiAuthRegisterMutationRequest;
    Errors: any;
};