/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateTaskManagerCommand } from "./CreateTaskManagerCommand.ts";

/**
 * @description OK
*/
export type PostApiTaskManager200 = any;

export type PostApiTaskManagerMutationRequest = CreateTaskManagerCommand;

export type PostApiTaskManagerMutationResponse = PostApiTaskManager200;

export type PostApiTaskManagerMutation = {
    Response: PostApiTaskManager200;
    Request: PostApiTaskManagerMutationRequest;
    Errors: any;
};