/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LoginUserCommand } from "./LoginUserCommand.ts";
import type { UserExtendVmResponseApiVm } from "./UserExtendVmResponseApiVm.ts";

/**
 * @description OK
*/
export type PostApiAuthLogin200 = UserExtendVmResponseApiVm;

export type PostApiAuthLoginMutationRequest = LoginUserCommand;

export type PostApiAuthLoginMutationResponse = PostApiAuthLogin200;

export type PostApiAuthLoginMutation = {
    Response: PostApiAuthLogin200;
    Request: PostApiAuthLoginMutationRequest;
    Errors: any;
};