/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LogoutUserCommand } from "./LogoutUserCommand.ts";

/**
 * @description OK
*/
export type PostApiAuthLogout200 = any;

export type PostApiAuthLogoutMutationRequest = LogoutUserCommand;

export type PostApiAuthLogoutMutationResponse = PostApiAuthLogout200;

export type PostApiAuthLogoutMutation = {
    Response: PostApiAuthLogout200;
    Request: PostApiAuthLogoutMutationRequest;
    Errors: any;
};