/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResponseApiVm } from "./ResponseApiVm.ts";
import type { SendEmailUserCommand } from "./SendEmailUserCommand.ts";

/**
 * @description OK
*/
export type PostApiAuthForgetPassword200 = ResponseApiVm;

export type PostApiAuthForgetPasswordMutationRequest = SendEmailUserCommand;

export type PostApiAuthForgetPasswordMutationResponse = PostApiAuthForgetPassword200;

export type PostApiAuthForgetPasswordMutation = {
    Response: PostApiAuthForgetPassword200;
    Request: PostApiAuthForgetPasswordMutationRequest;
    Errors: any;
};