/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description OK
*/
export type PutApiAuthUpdateProfile200 = any;

export type PutApiAuthUpdateProfileMutationRequest = {
    /**
     * @type string | undefined, binary
    */
    pathPhoto?: Blob;
};

export type PutApiAuthUpdateProfileMutationResponse = PutApiAuthUpdateProfile200;

export type PutApiAuthUpdateProfileMutation = {
    Response: PutApiAuthUpdateProfile200;
    Request: PutApiAuthUpdateProfileMutationRequest;
    Errors: any;
};