/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RegisterUserCommand = {
    /**
     * @type string
    */
    userName: string | null;
    /**
     * @type string
    */
    email: string | null;
    /**
     * @type string
    */
    password: string | null;
};