/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ResponseApiVm = {
    /**
     * @type boolean | undefined
    */
    status?: boolean;
    /**
     * @type array
    */
    message?: string[] | null;
    /**
     * @type array
    */
    errors?: string[] | null;
    /**
     * @type string
    */
    accessToken?: string | null;
    /**
     * @type string
    */
    refreshToken?: string | null;
    /**
     * @type integer, int32
    */
    currentPage?: number | null;
    /**
     * @type integer, int32
    */
    pageSize?: number | null;
    /**
     * @type integer, int32
    */
    totalCount?: number | null;
    /**
     * @type integer, int32
    */
    totalPages?: number | null;
    /**
     * @type integer, int32
    */
    statusCode?: number | null;
};