/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserExtendVm = {
    /**
     * @type string | undefined, uuid
    */
    id?: string;
    /**
     * @type string
    */
    userName?: string | null;
    /**
     * @type string
    */
    email?: string | null;
    /**
     * @type string
    */
    role?: string | null;
    /**
     * @type string
    */
    userPhoto?: string | null;
    /**
     * @type string
    */
    googleId?: string | null;
    /**
     * @type string, date-time
    */
    createdAt?: string | null;
    /**
     * @type string, date-time
    */
    updatedAt?: string | null;
};