export type { DeleteActivitiesIdMutationKey } from "./useDeleteActivitiesId.ts";
export type { DeleteJobRecommendationsIdMutationKey } from "./useDeleteJobRecommendationsId.ts";
export type { DeleteMenusIdMutationKey } from "./useDeleteMenusId.ts";
export type { GetActivitiesQueryKey } from "./useGetActivities.ts";
export type { GetActivitiesIdQueryKey } from "./useGetActivitiesId.ts";
export type { GetActivitiesIdSuspenseQueryKey } from "./useGetActivitiesIdSuspense.ts";
export type { GetActivitiesSuspenseQueryKey } from "./useGetActivitiesSuspense.ts";
export type { GetJobRecommendationsQueryKey } from "./useGetJobRecommendations.ts";
export type { GetJobRecommendationsIdQueryKey } from "./useGetJobRecommendationsId.ts";
export type { GetJobRecommendationsIdSuspenseQueryKey } from "./useGetJobRecommendationsIdSuspense.ts";
export type { GetJobRecommendationsSuspenseQueryKey } from "./useGetJobRecommendationsSuspense.ts";
export type { GetMenusQueryKey } from "./useGetMenus.ts";
export type { GetMenusIdQueryKey } from "./useGetMenusId.ts";
export type { GetMenusIdSuspenseQueryKey } from "./useGetMenusIdSuspense.ts";
export type { GetMenusSuspenseQueryKey } from "./useGetMenusSuspense.ts";
export type { GetProfileMeQueryKey } from "./useGetProfileMe.ts";
export type { GetProfileMeSuspenseQueryKey } from "./useGetProfileMeSuspense.ts";
export type { PostActivitiesMutationKey } from "./usePostActivities.ts";
export type { PostAuthLoginMutationKey } from "./usePostAuthLogin.ts";
export type { PostAuthLoginVerifyMutationKey } from "./usePostAuthLoginVerify.ts";
export type { PostAuthRegisterMutationKey } from "./usePostAuthRegister.ts";
export type { PostAuthVerifyOtpMutationKey } from "./usePostAuthVerifyOtp.ts";
export type { PostJobRecommendationsMutationKey } from "./usePostJobRecommendations.ts";
export type { PostMenusMutationKey } from "./usePostMenus.ts";
export type { PutActivitiesIdMutationKey } from "./usePutActivitiesId.ts";
export type { PutJobRecommendationsIdMutationKey } from "./usePutJobRecommendationsId.ts";
export type { PutMenusIdMutationKey } from "./usePutMenusId.ts";
export type { PutProfileMeMutationKey } from "./usePutProfileMe.ts";
export { deleteActivitiesIdMutationKey } from "./useDeleteActivitiesId.ts";
export { deleteActivitiesId } from "./useDeleteActivitiesId.ts";
export { deleteActivitiesIdMutationOptions } from "./useDeleteActivitiesId.ts";
export { useDeleteActivitiesId } from "./useDeleteActivitiesId.ts";
export { deleteJobRecommendationsIdMutationKey } from "./useDeleteJobRecommendationsId.ts";
export { deleteJobRecommendationsId } from "./useDeleteJobRecommendationsId.ts";
export { deleteJobRecommendationsIdMutationOptions } from "./useDeleteJobRecommendationsId.ts";
export { useDeleteJobRecommendationsId } from "./useDeleteJobRecommendationsId.ts";
export { deleteMenusIdMutationKey } from "./useDeleteMenusId.ts";
export { deleteMenusId } from "./useDeleteMenusId.ts";
export { deleteMenusIdMutationOptions } from "./useDeleteMenusId.ts";
export { useDeleteMenusId } from "./useDeleteMenusId.ts";
export { getActivitiesQueryKey } from "./useGetActivities.ts";
export { getActivities } from "./useGetActivities.ts";
export { getActivitiesQueryOptions } from "./useGetActivities.ts";
export { useGetActivities } from "./useGetActivities.ts";
export { getActivitiesIdQueryKey } from "./useGetActivitiesId.ts";
export { getActivitiesId } from "./useGetActivitiesId.ts";
export { getActivitiesIdQueryOptions } from "./useGetActivitiesId.ts";
export { useGetActivitiesId } from "./useGetActivitiesId.ts";
export { getActivitiesIdSuspenseQueryKey } from "./useGetActivitiesIdSuspense.ts";
export { getActivitiesIdSuspense } from "./useGetActivitiesIdSuspense.ts";
export { getActivitiesIdSuspenseQueryOptions } from "./useGetActivitiesIdSuspense.ts";
export { useGetActivitiesIdSuspense } from "./useGetActivitiesIdSuspense.ts";
export { getActivitiesSuspenseQueryKey } from "./useGetActivitiesSuspense.ts";
export { getActivitiesSuspense } from "./useGetActivitiesSuspense.ts";
export { getActivitiesSuspenseQueryOptions } from "./useGetActivitiesSuspense.ts";
export { useGetActivitiesSuspense } from "./useGetActivitiesSuspense.ts";
export { getJobRecommendationsQueryKey } from "./useGetJobRecommendations.ts";
export { getJobRecommendations } from "./useGetJobRecommendations.ts";
export { getJobRecommendationsQueryOptions } from "./useGetJobRecommendations.ts";
export { useGetJobRecommendations } from "./useGetJobRecommendations.ts";
export { getJobRecommendationsIdQueryKey } from "./useGetJobRecommendationsId.ts";
export { getJobRecommendationsId } from "./useGetJobRecommendationsId.ts";
export { getJobRecommendationsIdQueryOptions } from "./useGetJobRecommendationsId.ts";
export { useGetJobRecommendationsId } from "./useGetJobRecommendationsId.ts";
export { getJobRecommendationsIdSuspenseQueryKey } from "./useGetJobRecommendationsIdSuspense.ts";
export { getJobRecommendationsIdSuspense } from "./useGetJobRecommendationsIdSuspense.ts";
export { getJobRecommendationsIdSuspenseQueryOptions } from "./useGetJobRecommendationsIdSuspense.ts";
export { useGetJobRecommendationsIdSuspense } from "./useGetJobRecommendationsIdSuspense.ts";
export { getJobRecommendationsSuspenseQueryKey } from "./useGetJobRecommendationsSuspense.ts";
export { getJobRecommendationsSuspense } from "./useGetJobRecommendationsSuspense.ts";
export { getJobRecommendationsSuspenseQueryOptions } from "./useGetJobRecommendationsSuspense.ts";
export { useGetJobRecommendationsSuspense } from "./useGetJobRecommendationsSuspense.ts";
export { getMenusQueryKey } from "./useGetMenus.ts";
export { getMenus } from "./useGetMenus.ts";
export { getMenusQueryOptions } from "./useGetMenus.ts";
export { useGetMenus } from "./useGetMenus.ts";
export { getMenusIdQueryKey } from "./useGetMenusId.ts";
export { getMenusId } from "./useGetMenusId.ts";
export { getMenusIdQueryOptions } from "./useGetMenusId.ts";
export { useGetMenusId } from "./useGetMenusId.ts";
export { getMenusIdSuspenseQueryKey } from "./useGetMenusIdSuspense.ts";
export { getMenusIdSuspense } from "./useGetMenusIdSuspense.ts";
export { getMenusIdSuspenseQueryOptions } from "./useGetMenusIdSuspense.ts";
export { useGetMenusIdSuspense } from "./useGetMenusIdSuspense.ts";
export { getMenusSuspenseQueryKey } from "./useGetMenusSuspense.ts";
export { getMenusSuspense } from "./useGetMenusSuspense.ts";
export { getMenusSuspenseQueryOptions } from "./useGetMenusSuspense.ts";
export { useGetMenusSuspense } from "./useGetMenusSuspense.ts";
export { getProfileMeQueryKey } from "./useGetProfileMe.ts";
export { getProfileMe } from "./useGetProfileMe.ts";
export { getProfileMeQueryOptions } from "./useGetProfileMe.ts";
export { useGetProfileMe } from "./useGetProfileMe.ts";
export { getProfileMeSuspenseQueryKey } from "./useGetProfileMeSuspense.ts";
export { getProfileMeSuspense } from "./useGetProfileMeSuspense.ts";
export { getProfileMeSuspenseQueryOptions } from "./useGetProfileMeSuspense.ts";
export { useGetProfileMeSuspense } from "./useGetProfileMeSuspense.ts";
export { postActivitiesMutationKey } from "./usePostActivities.ts";
export { postActivities } from "./usePostActivities.ts";
export { postActivitiesMutationOptions } from "./usePostActivities.ts";
export { usePostActivities } from "./usePostActivities.ts";
export { postAuthLoginMutationKey } from "./usePostAuthLogin.ts";
export { postAuthLogin } from "./usePostAuthLogin.ts";
export { postAuthLoginMutationOptions } from "./usePostAuthLogin.ts";
export { usePostAuthLogin } from "./usePostAuthLogin.ts";
export { postAuthLoginVerifyMutationKey } from "./usePostAuthLoginVerify.ts";
export { postAuthLoginVerify } from "./usePostAuthLoginVerify.ts";
export { postAuthLoginVerifyMutationOptions } from "./usePostAuthLoginVerify.ts";
export { usePostAuthLoginVerify } from "./usePostAuthLoginVerify.ts";
export { postAuthRegisterMutationKey } from "./usePostAuthRegister.ts";
export { postAuthRegister } from "./usePostAuthRegister.ts";
export { postAuthRegisterMutationOptions } from "./usePostAuthRegister.ts";
export { usePostAuthRegister } from "./usePostAuthRegister.ts";
export { postAuthVerifyOtpMutationKey } from "./usePostAuthVerifyOtp.ts";
export { postAuthVerifyOtp } from "./usePostAuthVerifyOtp.ts";
export { postAuthVerifyOtpMutationOptions } from "./usePostAuthVerifyOtp.ts";
export { usePostAuthVerifyOtp } from "./usePostAuthVerifyOtp.ts";
export { postJobRecommendationsMutationKey } from "./usePostJobRecommendations.ts";
export { postJobRecommendations } from "./usePostJobRecommendations.ts";
export { postJobRecommendationsMutationOptions } from "./usePostJobRecommendations.ts";
export { usePostJobRecommendations } from "./usePostJobRecommendations.ts";
export { postMenusMutationKey } from "./usePostMenus.ts";
export { postMenus } from "./usePostMenus.ts";
export { postMenusMutationOptions } from "./usePostMenus.ts";
export { usePostMenus } from "./usePostMenus.ts";
export { putActivitiesIdMutationKey } from "./usePutActivitiesId.ts";
export { putActivitiesId } from "./usePutActivitiesId.ts";
export { putActivitiesIdMutationOptions } from "./usePutActivitiesId.ts";
export { usePutActivitiesId } from "./usePutActivitiesId.ts";
export { putJobRecommendationsIdMutationKey } from "./usePutJobRecommendationsId.ts";
export { putJobRecommendationsId } from "./usePutJobRecommendationsId.ts";
export { putJobRecommendationsIdMutationOptions } from "./usePutJobRecommendationsId.ts";
export { usePutJobRecommendationsId } from "./usePutJobRecommendationsId.ts";
export { putMenusIdMutationKey } from "./usePutMenusId.ts";
export { putMenusId } from "./usePutMenusId.ts";
export { putMenusIdMutationOptions } from "./usePutMenusId.ts";
export { usePutMenusId } from "./usePutMenusId.ts";
export { putProfileMeMutationKey } from "./usePutProfileMe.ts";
export { putProfileMe } from "./usePutProfileMe.ts";
export { putProfileMeMutationOptions } from "./usePutProfileMe.ts";
export { usePutProfileMe } from "./usePutProfileMe.ts";