/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeleteMenusIdMutationResponse, DeleteMenusIdPathParams } from "../types/DeleteMenusId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteMenusIdMutationKey = () => [{ url: '/menus/:id' }] as const

export type DeleteMenusIdMutationKey = ReturnType<typeof deleteMenusIdMutationKey>

/**
 * @summary Delete a menu
 * {@link /menus/:id}
 */
export async function deleteMenusId(id: DeleteMenusIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteMenusIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/menus/${id}`, ... requestConfig })  
  return res
}

export function deleteMenusIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteMenusIdMutationKey()
  return mutationOptions<ResponseConfig<DeleteMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteMenusIdPathParams["id"]}, TContext>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteMenusId(id, config)
    },
  })
}

/**
 * @summary Delete a menu
 * {@link /menus/:id}
 */
export function useDeleteMenusId<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<DeleteMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteMenusIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteMenusIdMutationKey()

  const baseOptions = deleteMenusIdMutationOptions(config) as UseMutationOptions<ResponseConfig<DeleteMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteMenusIdPathParams["id"]}, TContext>


  return useMutation<ResponseConfig<DeleteMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteMenusIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<DeleteMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteMenusIdPathParams["id"]}, TContext>
}