/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeleteActivitiesIdMutationResponse, DeleteActivitiesIdPathParams } from "../types/DeleteActivitiesId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteActivitiesIdMutationKey = () => [{ url: '/activities/:id' }] as const

export type DeleteActivitiesIdMutationKey = ReturnType<typeof deleteActivitiesIdMutationKey>

/**
 * @summary Delete an activity
 * {@link /activities/:id}
 */
export async function deleteActivitiesId(id: DeleteActivitiesIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteActivitiesIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/activities/${id}`, ... requestConfig })  
  return res
}

export function deleteActivitiesIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteActivitiesIdMutationKey()
  return mutationOptions<ResponseConfig<DeleteActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteActivitiesIdPathParams["id"]}, TContext>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteActivitiesId(id, config)
    },
  })
}

/**
 * @summary Delete an activity
 * {@link /activities/:id}
 */
export function useDeleteActivitiesId<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<DeleteActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteActivitiesIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteActivitiesIdMutationKey()

  const baseOptions = deleteActivitiesIdMutationOptions(config) as UseMutationOptions<ResponseConfig<DeleteActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteActivitiesIdPathParams["id"]}, TContext>


  return useMutation<ResponseConfig<DeleteActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteActivitiesIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<DeleteActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteActivitiesIdPathParams["id"]}, TContext>
}