/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeleteJobRecommendationsIdMutationResponse, DeleteJobRecommendationsIdPathParams } from "../types/DeleteJobRecommendationsId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteJobRecommendationsIdMutationKey = () => [{ url: '/job-recommendations/:id' }] as const

export type DeleteJobRecommendationsIdMutationKey = ReturnType<typeof deleteJobRecommendationsIdMutationKey>

/**
 * @summary Delete a job recommendation
 * {@link /job-recommendations/:id}
 */
export async function deleteJobRecommendationsId(id: DeleteJobRecommendationsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteJobRecommendationsIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/job-recommendations/${id}`, ... requestConfig })  
  return res
}

export function deleteJobRecommendationsIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteJobRecommendationsIdMutationKey()
  return mutationOptions<ResponseConfig<DeleteJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteJobRecommendationsIdPathParams["id"]}, TContext>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteJobRecommendationsId(id, config)
    },
  })
}

/**
 * @summary Delete a job recommendation
 * {@link /job-recommendations/:id}
 */
export function useDeleteJobRecommendationsId<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<DeleteJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteJobRecommendationsIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteJobRecommendationsIdMutationKey()

  const baseOptions = deleteJobRecommendationsIdMutationOptions(config) as UseMutationOptions<ResponseConfig<DeleteJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteJobRecommendationsIdPathParams["id"]}, TContext>


  return useMutation<ResponseConfig<DeleteJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteJobRecommendationsIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<DeleteJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: DeleteJobRecommendationsIdPathParams["id"]}, TContext>
}