/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetJobRecommendationsQueryResponse } from "../types/GetJobRecommendations.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getJobRecommendationsSuspenseQueryKey = () => [{ url: '/job-recommendations' }] as const

export type GetJobRecommendationsSuspenseQueryKey = ReturnType<typeof getJobRecommendationsSuspenseQueryKey>

/**
 * @summary Get all job recommendations
 * {@link /job-recommendations}
 */
export async function getJobRecommendationsSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetJobRecommendationsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/job-recommendations`, ... requestConfig })  
  return res
}

export function getJobRecommendationsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getJobRecommendationsSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetJobRecommendationsQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetJobRecommendationsQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getJobRecommendationsSuspense(config)
   },
  })
}

/**
 * @summary Get all job recommendations
 * {@link /job-recommendations}
 */
export function useGetJobRecommendationsSuspense<TData = ResponseConfig<GetJobRecommendationsQueryResponse>, TQueryKey extends QueryKey = GetJobRecommendationsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetJobRecommendationsQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getJobRecommendationsSuspenseQueryKey()


  const query = useSuspenseQuery({
   ...getJobRecommendationsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}