/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetJobRecommendationsIdQueryResponse, GetJobRecommendationsIdPathParams, GetJobRecommendationsId404 } from "../types/GetJobRecommendationsId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getJobRecommendationsIdQueryKey = (id: GetJobRecommendationsIdPathParams["id"]) => [{ url: '/job-recommendations/:id', params: {id:id} }] as const

export type GetJobRecommendationsIdQueryKey = ReturnType<typeof getJobRecommendationsIdQueryKey>

/**
 * @summary Get job recommendation by ID
 * {@link /job-recommendations/:id}
 */
export async function getJobRecommendationsId(id: GetJobRecommendationsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetJobRecommendationsIdQueryResponse, ResponseErrorConfig<GetJobRecommendationsId404>, unknown>({ method : "GET", url : `/job-recommendations/${id}`, ... requestConfig })  
  return res
}

export function getJobRecommendationsIdQueryOptions(id: GetJobRecommendationsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getJobRecommendationsIdQueryKey(id)
  return queryOptions<ResponseConfig<GetJobRecommendationsIdQueryResponse>, ResponseErrorConfig<GetJobRecommendationsId404>, ResponseConfig<GetJobRecommendationsIdQueryResponse>, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getJobRecommendationsId(id, config)
   },
  })
}

/**
 * @summary Get job recommendation by ID
 * {@link /job-recommendations/:id}
 */
export function useGetJobRecommendationsId<TData = ResponseConfig<GetJobRecommendationsIdQueryResponse>, TQueryData = ResponseConfig<GetJobRecommendationsIdQueryResponse>, TQueryKey extends QueryKey = GetJobRecommendationsIdQueryKey>(id: GetJobRecommendationsIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetJobRecommendationsIdQueryResponse>, ResponseErrorConfig<GetJobRecommendationsId404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getJobRecommendationsIdQueryKey(id)


  const query = useQuery({
   ...getJobRecommendationsIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetJobRecommendationsId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}