/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetJobRecommendationsIdQueryResponse, GetJobRecommendationsIdPathParams, GetJobRecommendationsId404 } from "../types/GetJobRecommendationsId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getJobRecommendationsIdSuspenseQueryKey = (id: GetJobRecommendationsIdPathParams["id"]) => [{ url: '/job-recommendations/:id', params: {id:id} }] as const

export type GetJobRecommendationsIdSuspenseQueryKey = ReturnType<typeof getJobRecommendationsIdSuspenseQueryKey>

/**
 * @summary Get job recommendation by ID
 * {@link /job-recommendations/:id}
 */
export async function getJobRecommendationsIdSuspense(id: GetJobRecommendationsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetJobRecommendationsIdQueryResponse, ResponseErrorConfig<GetJobRecommendationsId404>, unknown>({ method : "GET", url : `/job-recommendations/${id}`, ... requestConfig })  
  return res
}

export function getJobRecommendationsIdSuspenseQueryOptions(id: GetJobRecommendationsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getJobRecommendationsIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetJobRecommendationsIdQueryResponse>, ResponseErrorConfig<GetJobRecommendationsId404>, ResponseConfig<GetJobRecommendationsIdQueryResponse>, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getJobRecommendationsIdSuspense(id, config)
   },
  })
}

/**
 * @summary Get job recommendation by ID
 * {@link /job-recommendations/:id}
 */
export function useGetJobRecommendationsIdSuspense<TData = ResponseConfig<GetJobRecommendationsIdQueryResponse>, TQueryKey extends QueryKey = GetJobRecommendationsIdSuspenseQueryKey>(id: GetJobRecommendationsIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetJobRecommendationsIdQueryResponse>, ResponseErrorConfig<GetJobRecommendationsId404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getJobRecommendationsIdSuspenseQueryKey(id)


  const query = useSuspenseQuery({
   ...getJobRecommendationsIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetJobRecommendationsId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}