/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetMenusIdQueryResponse, GetMenusIdPathParams, GetMenusId404 } from "../types/GetMenusId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMenusIdQueryKey = (id: GetMenusIdPathParams["id"]) => [{ url: '/menus/:id', params: {id:id} }] as const

export type GetMenusIdQueryKey = ReturnType<typeof getMenusIdQueryKey>

/**
 * @summary Get menu by ID
 * {@link /menus/:id}
 */
export async function getMenusId(id: GetMenusIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMenusIdQueryResponse, ResponseErrorConfig<GetMenusId404>, unknown>({ method : "GET", url : `/menus/${id}`, ... requestConfig })  
  return res
}

export function getMenusIdQueryOptions(id: GetMenusIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMenusIdQueryKey(id)
  return queryOptions<ResponseConfig<GetMenusIdQueryResponse>, ResponseErrorConfig<GetMenusId404>, ResponseConfig<GetMenusIdQueryResponse>, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMenusId(id, config)
   },
  })
}

/**
 * @summary Get menu by ID
 * {@link /menus/:id}
 */
export function useGetMenusId<TData = ResponseConfig<GetMenusIdQueryResponse>, TQueryData = ResponseConfig<GetMenusIdQueryResponse>, TQueryKey extends QueryKey = GetMenusIdQueryKey>(id: GetMenusIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetMenusIdQueryResponse>, ResponseErrorConfig<GetMenusId404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMenusIdQueryKey(id)


  const query = useQuery({
   ...getMenusIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetMenusId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}