/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetMenusIdQueryResponse, GetMenusIdPathParams, GetMenusId404 } from "../types/GetMenusId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMenusIdSuspenseQueryKey = (id: GetMenusIdPathParams["id"]) => [{ url: '/menus/:id', params: {id:id} }] as const

export type GetMenusIdSuspenseQueryKey = ReturnType<typeof getMenusIdSuspenseQueryKey>

/**
 * @summary Get menu by ID
 * {@link /menus/:id}
 */
export async function getMenusIdSuspense(id: GetMenusIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMenusIdQueryResponse, ResponseErrorConfig<GetMenusId404>, unknown>({ method : "GET", url : `/menus/${id}`, ... requestConfig })  
  return res
}

export function getMenusIdSuspenseQueryOptions(id: GetMenusIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMenusIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetMenusIdQueryResponse>, ResponseErrorConfig<GetMenusId404>, ResponseConfig<GetMenusIdQueryResponse>, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMenusIdSuspense(id, config)
   },
  })
}

/**
 * @summary Get menu by ID
 * {@link /menus/:id}
 */
export function useGetMenusIdSuspense<TData = ResponseConfig<GetMenusIdQueryResponse>, TQueryKey extends QueryKey = GetMenusIdSuspenseQueryKey>(id: GetMenusIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetMenusIdQueryResponse>, ResponseErrorConfig<GetMenusId404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMenusIdSuspenseQueryKey(id)


  const query = useSuspenseQuery({
   ...getMenusIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetMenusId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}