/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetProfileMeQueryResponse, GetProfileMe401 } from "../types/GetProfileMe.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProfileMeSuspenseQueryKey = () => [{ url: '/profile/me' }] as const

export type GetProfileMeSuspenseQueryKey = ReturnType<typeof getProfileMeSuspenseQueryKey>

/**
 * @summary Get current user profile
 * {@link /profile/me}
 */
export async function getProfileMeSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetProfileMeQueryResponse, ResponseErrorConfig<GetProfileMe401>, unknown>({ method : "GET", url : `/profile/me`, ... requestConfig })  
  return res
}

export function getProfileMeSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getProfileMeSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetProfileMeQueryResponse>, ResponseErrorConfig<GetProfileMe401>, ResponseConfig<GetProfileMeQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getProfileMeSuspense(config)
   },
  })
}

/**
 * @summary Get current user profile
 * {@link /profile/me}
 */
export function useGetProfileMeSuspense<TData = ResponseConfig<GetProfileMeQueryResponse>, TQueryKey extends QueryKey = GetProfileMeSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetProfileMeQueryResponse>, ResponseErrorConfig<GetProfileMe401>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getProfileMeSuspenseQueryKey()


  const query = useSuspenseQuery({
   ...getProfileMeSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetProfileMe401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}