/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetActivitiesIdQueryResponse, GetActivitiesIdPathParams, GetActivitiesId404 } from "../types/GetActivitiesId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getActivitiesIdSuspenseQueryKey = (id: GetActivitiesIdPathParams["id"]) => [{ url: '/activities/:id', params: {id:id} }] as const

export type GetActivitiesIdSuspenseQueryKey = ReturnType<typeof getActivitiesIdSuspenseQueryKey>

/**
 * @summary Get activity by ID
 * {@link /activities/:id}
 */
export async function getActivitiesIdSuspense(id: GetActivitiesIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetActivitiesIdQueryResponse, ResponseErrorConfig<GetActivitiesId404>, unknown>({ method : "GET", url : `/activities/${id}`, ... requestConfig })  
  return res
}

export function getActivitiesIdSuspenseQueryOptions(id: GetActivitiesIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getActivitiesIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetActivitiesIdQueryResponse>, ResponseErrorConfig<GetActivitiesId404>, ResponseConfig<GetActivitiesIdQueryResponse>, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getActivitiesIdSuspense(id, config)
   },
  })
}

/**
 * @summary Get activity by ID
 * {@link /activities/:id}
 */
export function useGetActivitiesIdSuspense<TData = ResponseConfig<GetActivitiesIdQueryResponse>, TQueryKey extends QueryKey = GetActivitiesIdSuspenseQueryKey>(id: GetActivitiesIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetActivitiesIdQueryResponse>, ResponseErrorConfig<GetActivitiesId404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getActivitiesIdSuspenseQueryKey(id)


  const query = useSuspenseQuery({
   ...getActivitiesIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetActivitiesId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}