/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetProfileMeQueryResponse, GetProfileMe401 } from "../types/GetProfileMe.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getProfileMeQueryKey = () => [{ url: '/profile/me' }] as const

export type GetProfileMeQueryKey = ReturnType<typeof getProfileMeQueryKey>

/**
 * @summary Get current user profile
 * {@link /profile/me}
 */
export async function getProfileMe(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetProfileMeQueryResponse, ResponseErrorConfig<GetProfileMe401>, unknown>({ method : "GET", url : `/profile/me`, ... requestConfig })  
  return res
}

export function getProfileMeQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getProfileMeQueryKey()
  return queryOptions<ResponseConfig<GetProfileMeQueryResponse>, ResponseErrorConfig<GetProfileMe401>, ResponseConfig<GetProfileMeQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getProfileMe(config)
   },
  })
}

/**
 * @summary Get current user profile
 * {@link /profile/me}
 */
export function useGetProfileMe<TData = ResponseConfig<GetProfileMeQueryResponse>, TQueryData = ResponseConfig<GetProfileMeQueryResponse>, TQueryKey extends QueryKey = GetProfileMeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetProfileMeQueryResponse>, ResponseErrorConfig<GetProfileMe401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getProfileMeQueryKey()


  const query = useQuery({
   ...getProfileMeQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetProfileMe401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}