/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetJobRecommendationsQueryResponse } from "../types/GetJobRecommendations.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getJobRecommendationsQueryKey = () => [{ url: '/job-recommendations' }] as const

export type GetJobRecommendationsQueryKey = ReturnType<typeof getJobRecommendationsQueryKey>

/**
 * @summary Get all job recommendations
 * {@link /job-recommendations}
 */
export async function getJobRecommendations(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetJobRecommendationsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/job-recommendations`, ... requestConfig })  
  return res
}

export function getJobRecommendationsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getJobRecommendationsQueryKey()
  return queryOptions<ResponseConfig<GetJobRecommendationsQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetJobRecommendationsQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getJobRecommendations(config)
   },
  })
}

/**
 * @summary Get all job recommendations
 * {@link /job-recommendations}
 */
export function useGetJobRecommendations<TData = ResponseConfig<GetJobRecommendationsQueryResponse>, TQueryData = ResponseConfig<GetJobRecommendationsQueryResponse>, TQueryKey extends QueryKey = GetJobRecommendationsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetJobRecommendationsQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getJobRecommendationsQueryKey()


  const query = useQuery({
   ...getJobRecommendationsQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}