/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetActivitiesIdQueryResponse, GetActivitiesIdPathParams, GetActivitiesId404 } from "../types/GetActivitiesId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getActivitiesIdQueryKey = (id: GetActivitiesIdPathParams["id"]) => [{ url: '/activities/:id', params: {id:id} }] as const

export type GetActivitiesIdQueryKey = ReturnType<typeof getActivitiesIdQueryKey>

/**
 * @summary Get activity by ID
 * {@link /activities/:id}
 */
export async function getActivitiesId(id: GetActivitiesIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetActivitiesIdQueryResponse, ResponseErrorConfig<GetActivitiesId404>, unknown>({ method : "GET", url : `/activities/${id}`, ... requestConfig })  
  return res
}

export function getActivitiesIdQueryOptions(id: GetActivitiesIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getActivitiesIdQueryKey(id)
  return queryOptions<ResponseConfig<GetActivitiesIdQueryResponse>, ResponseErrorConfig<GetActivitiesId404>, ResponseConfig<GetActivitiesIdQueryResponse>, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getActivitiesId(id, config)
   },
  })
}

/**
 * @summary Get activity by ID
 * {@link /activities/:id}
 */
export function useGetActivitiesId<TData = ResponseConfig<GetActivitiesIdQueryResponse>, TQueryData = ResponseConfig<GetActivitiesIdQueryResponse>, TQueryKey extends QueryKey = GetActivitiesIdQueryKey>(id: GetActivitiesIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetActivitiesIdQueryResponse>, ResponseErrorConfig<GetActivitiesId404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getActivitiesIdQueryKey(id)


  const query = useQuery({
   ...getActivitiesIdQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetActivitiesId404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}