/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetActivitiesQueryResponse } from "../types/GetActivities.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getActivitiesSuspenseQueryKey = () => [{ url: '/activities' }] as const

export type GetActivitiesSuspenseQueryKey = ReturnType<typeof getActivitiesSuspenseQueryKey>

/**
 * @summary Get all activities
 * {@link /activities}
 */
export async function getActivitiesSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetActivitiesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/activities`, ... requestConfig })  
  return res
}

export function getActivitiesSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getActivitiesSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetActivitiesQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetActivitiesQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getActivitiesSuspense(config)
   },
  })
}

/**
 * @summary Get all activities
 * {@link /activities}
 */
export function useGetActivitiesSuspense<TData = ResponseConfig<GetActivitiesQueryResponse>, TQueryKey extends QueryKey = GetActivitiesSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetActivitiesQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getActivitiesSuspenseQueryKey()


  const query = useSuspenseQuery({
   ...getActivitiesSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}