/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetMenusQueryResponse } from "../types/GetMenus.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMenusQueryKey = () => [{ url: '/menus' }] as const

export type GetMenusQueryKey = ReturnType<typeof getMenusQueryKey>

/**
 * @summary Get all menus
 * {@link /menus}
 */
export async function getMenus(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMenusQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/menus`, ... requestConfig })  
  return res
}

export function getMenusQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMenusQueryKey()
  return queryOptions<ResponseConfig<GetMenusQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetMenusQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMenus(config)
   },
  })
}

/**
 * @summary Get all menus
 * {@link /menus}
 */
export function useGetMenus<TData = ResponseConfig<GetMenusQueryResponse>, TQueryData = ResponseConfig<GetMenusQueryResponse>, TQueryKey extends QueryKey = GetMenusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetMenusQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMenusQueryKey()


  const query = useQuery({
   ...getMenusQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}