/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetMenusQueryResponse } from "../types/GetMenus.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMenusSuspenseQueryKey = () => [{ url: '/menus' }] as const

export type GetMenusSuspenseQueryKey = ReturnType<typeof getMenusSuspenseQueryKey>

/**
 * @summary Get all menus
 * {@link /menus}
 */
export async function getMenusSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMenusQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/menus`, ... requestConfig })  
  return res
}

export function getMenusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMenusSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetMenusQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetMenusQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMenusSuspense(config)
   },
  })
}

/**
 * @summary Get all menus
 * {@link /menus}
 */
export function useGetMenusSuspense<TData = ResponseConfig<GetMenusQueryResponse>, TQueryKey extends QueryKey = GetMenusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetMenusQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMenusSuspenseQueryKey()


  const query = useSuspenseQuery({
   ...getMenusSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}