/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetActivitiesQueryResponse } from "../types/GetActivities.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getActivitiesQueryKey = () => [{ url: '/activities' }] as const

export type GetActivitiesQueryKey = ReturnType<typeof getActivitiesQueryKey>

/**
 * @summary Get all activities
 * {@link /activities}
 */
export async function getActivities(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetActivitiesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/activities`, ... requestConfig })  
  return res
}

export function getActivitiesQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getActivitiesQueryKey()
  return queryOptions<ResponseConfig<GetActivitiesQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetActivitiesQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getActivities(config)
   },
  })
}

/**
 * @summary Get all activities
 * {@link /activities}
 */
export function useGetActivities<TData = ResponseConfig<GetActivitiesQueryResponse>, TQueryData = ResponseConfig<GetActivitiesQueryResponse>, TQueryKey extends QueryKey = GetActivitiesQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetActivitiesQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getActivitiesQueryKey()


  const query = useQuery({
   ...getActivitiesQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}