/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostAuthRegisterMutationRequest, PostAuthRegisterMutationResponse, PostAuthRegister400 } from "../types/PostAuthRegister.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthRegisterMutationKey = () => [{ url: '/auth/register' }] as const

export type PostAuthRegisterMutationKey = ReturnType<typeof postAuthRegisterMutationKey>

/**
 * @summary Register a new user
 * {@link /auth/register}
 */
export async function postAuthRegister(data: PostAuthRegisterMutationRequest, config: Partial<RequestConfig<PostAuthRegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostAuthRegisterMutationResponse, ResponseErrorConfig<PostAuthRegister400>, PostAuthRegisterMutationRequest>({ method : "POST", url : `/auth/register`, data : requestData, ... requestConfig })  
  return res
}

export function postAuthRegisterMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostAuthRegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postAuthRegisterMutationKey()
  return mutationOptions<ResponseConfig<PostAuthRegisterMutationResponse>, ResponseErrorConfig<PostAuthRegister400>, {data: PostAuthRegisterMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postAuthRegister(data, config)
    },
  })
}

/**
 * @summary Register a new user
 * {@link /auth/register}
 */
export function usePostAuthRegister<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostAuthRegisterMutationResponse>, ResponseErrorConfig<PostAuthRegister400>, {data: PostAuthRegisterMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostAuthRegisterMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postAuthRegisterMutationKey()

  const baseOptions = postAuthRegisterMutationOptions(config) as UseMutationOptions<ResponseConfig<PostAuthRegisterMutationResponse>, ResponseErrorConfig<PostAuthRegister400>, {data: PostAuthRegisterMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostAuthRegisterMutationResponse>, ResponseErrorConfig<PostAuthRegister400>, {data: PostAuthRegisterMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostAuthRegisterMutationResponse>, ResponseErrorConfig<PostAuthRegister400>, {data: PostAuthRegisterMutationRequest}, TContext>
}