/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PutJobRecommendationsIdMutationRequest, PutJobRecommendationsIdMutationResponse, PutJobRecommendationsIdPathParams } from "../types/PutJobRecommendationsId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putJobRecommendationsIdMutationKey = () => [{ url: '/job-recommendations/:id' }] as const

export type PutJobRecommendationsIdMutationKey = ReturnType<typeof putJobRecommendationsIdMutationKey>

/**
 * @summary Update a job recommendation
 * {@link /job-recommendations/:id}
 */
export async function putJobRecommendationsId(id: PutJobRecommendationsIdPathParams["id"], data?: PutJobRecommendationsIdMutationRequest, config: Partial<RequestConfig<PutJobRecommendationsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutJobRecommendationsIdMutationResponse, ResponseErrorConfig<Error>, PutJobRecommendationsIdMutationRequest>({ method : "PUT", url : `/job-recommendations/${id}`, data : requestData, ... requestConfig })  
  return res
}

export function putJobRecommendationsIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutJobRecommendationsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putJobRecommendationsIdMutationKey()
  return mutationOptions<ResponseConfig<PutJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutJobRecommendationsIdPathParams["id"], data?: PutJobRecommendationsIdMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putJobRecommendationsId(id, data, config)
    },
  })
}

/**
 * @summary Update a job recommendation
 * {@link /job-recommendations/:id}
 */
export function usePutJobRecommendationsId<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PutJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutJobRecommendationsIdPathParams["id"], data?: PutJobRecommendationsIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutJobRecommendationsIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putJobRecommendationsIdMutationKey()

  const baseOptions = putJobRecommendationsIdMutationOptions(config) as UseMutationOptions<ResponseConfig<PutJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutJobRecommendationsIdPathParams["id"], data?: PutJobRecommendationsIdMutationRequest}, TContext>


  return useMutation<ResponseConfig<PutJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutJobRecommendationsIdPathParams["id"], data?: PutJobRecommendationsIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PutJobRecommendationsIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutJobRecommendationsIdPathParams["id"], data?: PutJobRecommendationsIdMutationRequest}, TContext>
}