/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PutMenusIdMutationRequest, PutMenusIdMutationResponse, PutMenusIdPathParams } from "../types/PutMenusId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putMenusIdMutationKey = () => [{ url: '/menus/:id' }] as const

export type PutMenusIdMutationKey = ReturnType<typeof putMenusIdMutationKey>

/**
 * @summary Update a menu
 * {@link /menus/:id}
 */
export async function putMenusId(id: PutMenusIdPathParams["id"], data?: PutMenusIdMutationRequest, config: Partial<RequestConfig<PutMenusIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutMenusIdMutationResponse, ResponseErrorConfig<Error>, PutMenusIdMutationRequest>({ method : "PUT", url : `/menus/${id}`, data : requestData, ... requestConfig })  
  return res
}

export function putMenusIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutMenusIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putMenusIdMutationKey()
  return mutationOptions<ResponseConfig<PutMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutMenusIdPathParams["id"], data?: PutMenusIdMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putMenusId(id, data, config)
    },
  })
}

/**
 * @summary Update a menu
 * {@link /menus/:id}
 */
export function usePutMenusId<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PutMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutMenusIdPathParams["id"], data?: PutMenusIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutMenusIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putMenusIdMutationKey()

  const baseOptions = putMenusIdMutationOptions(config) as UseMutationOptions<ResponseConfig<PutMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutMenusIdPathParams["id"], data?: PutMenusIdMutationRequest}, TContext>


  return useMutation<ResponseConfig<PutMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutMenusIdPathParams["id"], data?: PutMenusIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PutMenusIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutMenusIdPathParams["id"], data?: PutMenusIdMutationRequest}, TContext>
}