/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostActivitiesMutationRequest, PostActivitiesMutationResponse } from "../types/PostActivities.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postActivitiesMutationKey = () => [{ url: '/activities' }] as const

export type PostActivitiesMutationKey = ReturnType<typeof postActivitiesMutationKey>

/**
 * @summary Create a new activity
 * {@link /activities}
 */
export async function postActivities(data: PostActivitiesMutationRequest, config: Partial<RequestConfig<PostActivitiesMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostActivitiesMutationResponse, ResponseErrorConfig<Error>, PostActivitiesMutationRequest>({ method : "POST", url : `/activities`, data : requestData, ... requestConfig })  
  return res
}

export function postActivitiesMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostActivitiesMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postActivitiesMutationKey()
  return mutationOptions<ResponseConfig<PostActivitiesMutationResponse>, ResponseErrorConfig<Error>, {data: PostActivitiesMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postActivities(data, config)
    },
  })
}

/**
 * @summary Create a new activity
 * {@link /activities}
 */
export function usePostActivities<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostActivitiesMutationResponse>, ResponseErrorConfig<Error>, {data: PostActivitiesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostActivitiesMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postActivitiesMutationKey()

  const baseOptions = postActivitiesMutationOptions(config) as UseMutationOptions<ResponseConfig<PostActivitiesMutationResponse>, ResponseErrorConfig<Error>, {data: PostActivitiesMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostActivitiesMutationResponse>, ResponseErrorConfig<Error>, {data: PostActivitiesMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostActivitiesMutationResponse>, ResponseErrorConfig<Error>, {data: PostActivitiesMutationRequest}, TContext>
}