/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostAuthLoginMutationRequest, PostAuthLoginMutationResponse, PostAuthLogin401 } from "../types/PostAuthLogin.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthLoginMutationKey = () => [{ url: '/auth/login' }] as const

export type PostAuthLoginMutationKey = ReturnType<typeof postAuthLoginMutationKey>

/**
 * @summary Initiate login (Sends OTP)
 * {@link /auth/login}
 */
export async function postAuthLogin(data: PostAuthLoginMutationRequest, config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostAuthLoginMutationResponse, ResponseErrorConfig<PostAuthLogin401>, PostAuthLoginMutationRequest>({ method : "POST", url : `/auth/login`, data : requestData, ... requestConfig })  
  return res
}

export function postAuthLoginMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postAuthLoginMutationKey()
  return mutationOptions<ResponseConfig<PostAuthLoginMutationResponse>, ResponseErrorConfig<PostAuthLogin401>, {data: PostAuthLoginMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postAuthLogin(data, config)
    },
  })
}

/**
 * @summary Initiate login (Sends OTP)
 * {@link /auth/login}
 */
export function usePostAuthLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostAuthLoginMutationResponse>, ResponseErrorConfig<PostAuthLogin401>, {data: PostAuthLoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postAuthLoginMutationKey()

  const baseOptions = postAuthLoginMutationOptions(config) as UseMutationOptions<ResponseConfig<PostAuthLoginMutationResponse>, ResponseErrorConfig<PostAuthLogin401>, {data: PostAuthLoginMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostAuthLoginMutationResponse>, ResponseErrorConfig<PostAuthLogin401>, {data: PostAuthLoginMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostAuthLoginMutationResponse>, ResponseErrorConfig<PostAuthLogin401>, {data: PostAuthLoginMutationRequest}, TContext>
}