/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostAuthLoginVerifyMutationRequest, PostAuthLoginVerifyMutationResponse, PostAuthLoginVerify400 } from "../types/PostAuthLoginVerify.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthLoginVerifyMutationKey = () => [{ url: '/auth/login/verify' }] as const

export type PostAuthLoginVerifyMutationKey = ReturnType<typeof postAuthLoginVerifyMutationKey>

/**
 * @summary Verify login OTP and get token
 * {@link /auth/login/verify}
 */
export async function postAuthLoginVerify(data: PostAuthLoginVerifyMutationRequest, config: Partial<RequestConfig<PostAuthLoginVerifyMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostAuthLoginVerifyMutationResponse, ResponseErrorConfig<PostAuthLoginVerify400>, PostAuthLoginVerifyMutationRequest>({ method : "POST", url : `/auth/login/verify`, data : requestData, ... requestConfig })  
  return res
}

export function postAuthLoginVerifyMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostAuthLoginVerifyMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postAuthLoginVerifyMutationKey()
  return mutationOptions<ResponseConfig<PostAuthLoginVerifyMutationResponse>, ResponseErrorConfig<PostAuthLoginVerify400>, {data: PostAuthLoginVerifyMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postAuthLoginVerify(data, config)
    },
  })
}

/**
 * @summary Verify login OTP and get token
 * {@link /auth/login/verify}
 */
export function usePostAuthLoginVerify<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostAuthLoginVerifyMutationResponse>, ResponseErrorConfig<PostAuthLoginVerify400>, {data: PostAuthLoginVerifyMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostAuthLoginVerifyMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postAuthLoginVerifyMutationKey()

  const baseOptions = postAuthLoginVerifyMutationOptions(config) as UseMutationOptions<ResponseConfig<PostAuthLoginVerifyMutationResponse>, ResponseErrorConfig<PostAuthLoginVerify400>, {data: PostAuthLoginVerifyMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostAuthLoginVerifyMutationResponse>, ResponseErrorConfig<PostAuthLoginVerify400>, {data: PostAuthLoginVerifyMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostAuthLoginVerifyMutationResponse>, ResponseErrorConfig<PostAuthLoginVerify400>, {data: PostAuthLoginVerifyMutationRequest}, TContext>
}