/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostAuthVerifyOtpMutationRequest, PostAuthVerifyOtpMutationResponse, PostAuthVerifyOtp400 } from "../types/PostAuthVerifyOtp.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthVerifyOtpMutationKey = () => [{ url: '/auth/verify-otp' }] as const

export type PostAuthVerifyOtpMutationKey = ReturnType<typeof postAuthVerifyOtpMutationKey>

/**
 * @summary Verify OTP for account activation
 * {@link /auth/verify-otp}
 */
export async function postAuthVerifyOtp(data: PostAuthVerifyOtpMutationRequest, config: Partial<RequestConfig<PostAuthVerifyOtpMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostAuthVerifyOtpMutationResponse, ResponseErrorConfig<PostAuthVerifyOtp400>, PostAuthVerifyOtpMutationRequest>({ method : "POST", url : `/auth/verify-otp`, data : requestData, ... requestConfig })  
  return res
}

export function postAuthVerifyOtpMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostAuthVerifyOtpMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postAuthVerifyOtpMutationKey()
  return mutationOptions<ResponseConfig<PostAuthVerifyOtpMutationResponse>, ResponseErrorConfig<PostAuthVerifyOtp400>, {data: PostAuthVerifyOtpMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postAuthVerifyOtp(data, config)
    },
  })
}

/**
 * @summary Verify OTP for account activation
 * {@link /auth/verify-otp}
 */
export function usePostAuthVerifyOtp<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostAuthVerifyOtpMutationResponse>, ResponseErrorConfig<PostAuthVerifyOtp400>, {data: PostAuthVerifyOtpMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostAuthVerifyOtpMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postAuthVerifyOtpMutationKey()

  const baseOptions = postAuthVerifyOtpMutationOptions(config) as UseMutationOptions<ResponseConfig<PostAuthVerifyOtpMutationResponse>, ResponseErrorConfig<PostAuthVerifyOtp400>, {data: PostAuthVerifyOtpMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostAuthVerifyOtpMutationResponse>, ResponseErrorConfig<PostAuthVerifyOtp400>, {data: PostAuthVerifyOtpMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostAuthVerifyOtpMutationResponse>, ResponseErrorConfig<PostAuthVerifyOtp400>, {data: PostAuthVerifyOtpMutationRequest}, TContext>
}