/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostJobRecommendationsMutationRequest, PostJobRecommendationsMutationResponse } from "../types/PostJobRecommendations.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postJobRecommendationsMutationKey = () => [{ url: '/job-recommendations' }] as const

export type PostJobRecommendationsMutationKey = ReturnType<typeof postJobRecommendationsMutationKey>

/**
 * @summary Create a new job recommendation
 * {@link /job-recommendations}
 */
export async function postJobRecommendations(data: PostJobRecommendationsMutationRequest, config: Partial<RequestConfig<PostJobRecommendationsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostJobRecommendationsMutationResponse, ResponseErrorConfig<Error>, PostJobRecommendationsMutationRequest>({ method : "POST", url : `/job-recommendations`, data : requestData, ... requestConfig })  
  return res
}

export function postJobRecommendationsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostJobRecommendationsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postJobRecommendationsMutationKey()
  return mutationOptions<ResponseConfig<PostJobRecommendationsMutationResponse>, ResponseErrorConfig<Error>, {data: PostJobRecommendationsMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postJobRecommendations(data, config)
    },
  })
}

/**
 * @summary Create a new job recommendation
 * {@link /job-recommendations}
 */
export function usePostJobRecommendations<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostJobRecommendationsMutationResponse>, ResponseErrorConfig<Error>, {data: PostJobRecommendationsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostJobRecommendationsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postJobRecommendationsMutationKey()

  const baseOptions = postJobRecommendationsMutationOptions(config) as UseMutationOptions<ResponseConfig<PostJobRecommendationsMutationResponse>, ResponseErrorConfig<Error>, {data: PostJobRecommendationsMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostJobRecommendationsMutationResponse>, ResponseErrorConfig<Error>, {data: PostJobRecommendationsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostJobRecommendationsMutationResponse>, ResponseErrorConfig<Error>, {data: PostJobRecommendationsMutationRequest}, TContext>
}