/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostMenusMutationRequest, PostMenusMutationResponse } from "../types/PostMenus.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postMenusMutationKey = () => [{ url: '/menus' }] as const

export type PostMenusMutationKey = ReturnType<typeof postMenusMutationKey>

/**
 * @summary Create a new menu
 * {@link /menus}
 */
export async function postMenus(data: PostMenusMutationRequest, config: Partial<RequestConfig<PostMenusMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostMenusMutationResponse, ResponseErrorConfig<Error>, PostMenusMutationRequest>({ method : "POST", url : `/menus`, data : requestData, ... requestConfig })  
  return res
}

export function postMenusMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostMenusMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postMenusMutationKey()
  return mutationOptions<ResponseConfig<PostMenusMutationResponse>, ResponseErrorConfig<Error>, {data: PostMenusMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postMenus(data, config)
    },
  })
}

/**
 * @summary Create a new menu
 * {@link /menus}
 */
export function usePostMenus<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostMenusMutationResponse>, ResponseErrorConfig<Error>, {data: PostMenusMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostMenusMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postMenusMutationKey()

  const baseOptions = postMenusMutationOptions(config) as UseMutationOptions<ResponseConfig<PostMenusMutationResponse>, ResponseErrorConfig<Error>, {data: PostMenusMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostMenusMutationResponse>, ResponseErrorConfig<Error>, {data: PostMenusMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostMenusMutationResponse>, ResponseErrorConfig<Error>, {data: PostMenusMutationRequest}, TContext>
}