/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PutActivitiesIdMutationRequest, PutActivitiesIdMutationResponse, PutActivitiesIdPathParams } from "../types/PutActivitiesId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putActivitiesIdMutationKey = () => [{ url: '/activities/:id' }] as const

export type PutActivitiesIdMutationKey = ReturnType<typeof putActivitiesIdMutationKey>

/**
 * @summary Update an activity
 * {@link /activities/:id}
 */
export async function putActivitiesId(id: PutActivitiesIdPathParams["id"], data?: PutActivitiesIdMutationRequest, config: Partial<RequestConfig<PutActivitiesIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutActivitiesIdMutationResponse, ResponseErrorConfig<Error>, PutActivitiesIdMutationRequest>({ method : "PUT", url : `/activities/${id}`, data : requestData, ... requestConfig })  
  return res
}

export function putActivitiesIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutActivitiesIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putActivitiesIdMutationKey()
  return mutationOptions<ResponseConfig<PutActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutActivitiesIdPathParams["id"], data?: PutActivitiesIdMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putActivitiesId(id, data, config)
    },
  })
}

/**
 * @summary Update an activity
 * {@link /activities/:id}
 */
export function usePutActivitiesId<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PutActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutActivitiesIdPathParams["id"], data?: PutActivitiesIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutActivitiesIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putActivitiesIdMutationKey()

  const baseOptions = putActivitiesIdMutationOptions(config) as UseMutationOptions<ResponseConfig<PutActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutActivitiesIdPathParams["id"], data?: PutActivitiesIdMutationRequest}, TContext>


  return useMutation<ResponseConfig<PutActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutActivitiesIdPathParams["id"], data?: PutActivitiesIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PutActivitiesIdMutationResponse>, ResponseErrorConfig<Error>, {id: PutActivitiesIdPathParams["id"], data?: PutActivitiesIdMutationRequest}, TContext>
}