/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PutProfileMeMutationRequest, PutProfileMeMutationResponse, PutProfileMe401 } from "../types/PutProfileMe.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putProfileMeMutationKey = () => [{ url: '/profile/me' }] as const

export type PutProfileMeMutationKey = ReturnType<typeof putProfileMeMutationKey>

/**
 * @summary Update user profile
 * {@link /profile/me}
 */
export async function putProfileMe(data?: PutProfileMeMutationRequest, config: Partial<RequestConfig<PutProfileMeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutProfileMeMutationResponse, ResponseErrorConfig<PutProfileMe401>, PutProfileMeMutationRequest>({ method : "PUT", url : `/profile/me`, data : requestData, ... requestConfig })  
  return res
}

export function putProfileMeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutProfileMeMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putProfileMeMutationKey()
  return mutationOptions<ResponseConfig<PutProfileMeMutationResponse>, ResponseErrorConfig<PutProfileMe401>, {data?: PutProfileMeMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return putProfileMe(data, config)
    },
  })
}

/**
 * @summary Update user profile
 * {@link /profile/me}
 */
export function usePutProfileMe<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PutProfileMeMutationResponse>, ResponseErrorConfig<PutProfileMe401>, {data?: PutProfileMeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutProfileMeMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putProfileMeMutationKey()

  const baseOptions = putProfileMeMutationOptions(config) as UseMutationOptions<ResponseConfig<PutProfileMeMutationResponse>, ResponseErrorConfig<PutProfileMe401>, {data?: PutProfileMeMutationRequest}, TContext>


  return useMutation<ResponseConfig<PutProfileMeMutationResponse>, ResponseErrorConfig<PutProfileMe401>, {data?: PutProfileMeMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PutProfileMeMutationResponse>, ResponseErrorConfig<PutProfileMe401>, {data?: PutProfileMeMutationRequest}, TContext>
}