export type { DeleteActivitiesIdMutationKey } from "./hooks/useDeleteActivitiesId.ts";
export type { DeleteJobRecommendationsIdMutationKey } from "./hooks/useDeleteJobRecommendationsId.ts";
export type { DeleteMenusIdMutationKey } from "./hooks/useDeleteMenusId.ts";
export type { GetActivitiesQueryKey } from "./hooks/useGetActivities.ts";
export type { GetActivitiesIdQueryKey } from "./hooks/useGetActivitiesId.ts";
export type { GetActivitiesIdSuspenseQueryKey } from "./hooks/useGetActivitiesIdSuspense.ts";
export type { GetActivitiesSuspenseQueryKey } from "./hooks/useGetActivitiesSuspense.ts";
export type { GetJobRecommendationsQueryKey } from "./hooks/useGetJobRecommendations.ts";
export type { GetJobRecommendationsIdQueryKey } from "./hooks/useGetJobRecommendationsId.ts";
export type { GetJobRecommendationsIdSuspenseQueryKey } from "./hooks/useGetJobRecommendationsIdSuspense.ts";
export type { GetJobRecommendationsSuspenseQueryKey } from "./hooks/useGetJobRecommendationsSuspense.ts";
export type { GetMenusQueryKey } from "./hooks/useGetMenus.ts";
export type { GetMenusIdQueryKey } from "./hooks/useGetMenusId.ts";
export type { GetMenusIdSuspenseQueryKey } from "./hooks/useGetMenusIdSuspense.ts";
export type { GetMenusSuspenseQueryKey } from "./hooks/useGetMenusSuspense.ts";
export type { GetProfileMeQueryKey } from "./hooks/useGetProfileMe.ts";
export type { GetProfileMeSuspenseQueryKey } from "./hooks/useGetProfileMeSuspense.ts";
export type { PostActivitiesMutationKey } from "./hooks/usePostActivities.ts";
export type { PostAuthLoginMutationKey } from "./hooks/usePostAuthLogin.ts";
export type { PostAuthLoginVerifyMutationKey } from "./hooks/usePostAuthLoginVerify.ts";
export type { PostAuthRegisterMutationKey } from "./hooks/usePostAuthRegister.ts";
export type { PostAuthVerifyOtpMutationKey } from "./hooks/usePostAuthVerifyOtp.ts";
export type { PostJobRecommendationsMutationKey } from "./hooks/usePostJobRecommendations.ts";
export type { PostMenusMutationKey } from "./hooks/usePostMenus.ts";
export type { PutActivitiesIdMutationKey } from "./hooks/usePutActivitiesId.ts";
export type { PutJobRecommendationsIdMutationKey } from "./hooks/usePutJobRecommendationsId.ts";
export type { PutMenusIdMutationKey } from "./hooks/usePutMenusId.ts";
export type { PutProfileMeMutationKey } from "./hooks/usePutProfileMe.ts";
export type { DeleteActivitiesIdPathParams, DeleteActivitiesId204, DeleteActivitiesIdMutationResponse, DeleteActivitiesIdMutation } from "./types/DeleteActivitiesId.ts";
export type { DeleteJobRecommendationsIdPathParams, DeleteJobRecommendationsId204, DeleteJobRecommendationsIdMutationResponse, DeleteJobRecommendationsIdMutation } from "./types/DeleteJobRecommendationsId.ts";
export type { DeleteMenusIdPathParams, DeleteMenusId204, DeleteMenusIdMutationResponse, DeleteMenusIdMutation } from "./types/DeleteMenusId.ts";
export type { GetActivities200, GetActivitiesQueryResponse, GetActivitiesQuery } from "./types/GetActivities.ts";
export type { GetActivitiesIdPathParams, GetActivitiesId200, GetActivitiesId404, GetActivitiesIdQueryResponse, GetActivitiesIdQuery } from "./types/GetActivitiesId.ts";
export type { GetJobRecommendations200, GetJobRecommendationsQueryResponse, GetJobRecommendationsQuery } from "./types/GetJobRecommendations.ts";
export type { GetJobRecommendationsIdPathParams, GetJobRecommendationsId200, GetJobRecommendationsId404, GetJobRecommendationsIdQueryResponse, GetJobRecommendationsIdQuery } from "./types/GetJobRecommendationsId.ts";
export type { GetMenus200, GetMenusQueryResponse, GetMenusQuery } from "./types/GetMenus.ts";
export type { GetMenusIdPathParams, GetMenusId200, GetMenusId404, GetMenusIdQueryResponse, GetMenusIdQuery } from "./types/GetMenusId.ts";
export type { GetProfileMe200, GetProfileMe401, GetProfileMeQueryResponse, GetProfileMeQuery } from "./types/GetProfileMe.ts";
export type { PostActivities201, PostActivitiesMutationRequest, PostActivitiesMutationResponse, PostActivitiesMutation } from "./types/PostActivities.ts";
export type { PostAuthLogin200, PostAuthLogin401, PostAuthLoginMutationRequest, PostAuthLoginMutationResponse, PostAuthLoginMutation } from "./types/PostAuthLogin.ts";
export type { PostAuthLoginVerify200, PostAuthLoginVerify400, PostAuthLoginVerifyMutationRequest, PostAuthLoginVerifyMutationResponse, PostAuthLoginVerifyMutation } from "./types/PostAuthLoginVerify.ts";
export type { PostAuthRegister201, PostAuthRegister400, PostAuthRegisterMutationRequest, PostAuthRegisterMutationResponse, PostAuthRegisterMutation } from "./types/PostAuthRegister.ts";
export type { PostAuthVerifyOtp200, PostAuthVerifyOtp400, PostAuthVerifyOtpMutationRequest, PostAuthVerifyOtpMutationResponse, PostAuthVerifyOtpMutation } from "./types/PostAuthVerifyOtp.ts";
export type { PostJobRecommendations201, PostJobRecommendationsMutationRequest, PostJobRecommendationsMutationResponse, PostJobRecommendationsMutation } from "./types/PostJobRecommendations.ts";
export type { PostMenus201, PostMenusMutationRequest, PostMenusMutationResponse, PostMenusMutation } from "./types/PostMenus.ts";
export type { PutActivitiesIdPathParams, PutActivitiesId200, PutActivitiesIdMutationRequest, PutActivitiesIdMutationResponse, PutActivitiesIdMutation } from "./types/PutActivitiesId.ts";
export type { PutJobRecommendationsIdPathParams, PutJobRecommendationsId200, PutJobRecommendationsIdMutationRequest, PutJobRecommendationsIdMutationResponse, PutJobRecommendationsIdMutation } from "./types/PutJobRecommendationsId.ts";
export type { PutMenusIdPathParams, PutMenusId200, PutMenusIdMutationRequest, PutMenusIdMutationResponse, PutMenusIdMutation } from "./types/PutMenusId.ts";
export type { PutProfileMe200, PutProfileMe401, PutProfileMeMutationRequest, PutProfileMeMutationResponse, PutProfileMeMutation } from "./types/PutProfileMe.ts";
export { deleteActivitiesIdMutationKey } from "./hooks/useDeleteActivitiesId.ts";
export { deleteActivitiesId } from "./hooks/useDeleteActivitiesId.ts";
export { deleteActivitiesIdMutationOptions } from "./hooks/useDeleteActivitiesId.ts";
export { useDeleteActivitiesId } from "./hooks/useDeleteActivitiesId.ts";
export { deleteJobRecommendationsIdMutationKey } from "./hooks/useDeleteJobRecommendationsId.ts";
export { deleteJobRecommendationsId } from "./hooks/useDeleteJobRecommendationsId.ts";
export { deleteJobRecommendationsIdMutationOptions } from "./hooks/useDeleteJobRecommendationsId.ts";
export { useDeleteJobRecommendationsId } from "./hooks/useDeleteJobRecommendationsId.ts";
export { deleteMenusIdMutationKey } from "./hooks/useDeleteMenusId.ts";
export { deleteMenusId } from "./hooks/useDeleteMenusId.ts";
export { deleteMenusIdMutationOptions } from "./hooks/useDeleteMenusId.ts";
export { useDeleteMenusId } from "./hooks/useDeleteMenusId.ts";
export { getActivitiesQueryKey } from "./hooks/useGetActivities.ts";
export { getActivities } from "./hooks/useGetActivities.ts";
export { getActivitiesQueryOptions } from "./hooks/useGetActivities.ts";
export { useGetActivities } from "./hooks/useGetActivities.ts";
export { getActivitiesIdQueryKey } from "./hooks/useGetActivitiesId.ts";
export { getActivitiesId } from "./hooks/useGetActivitiesId.ts";
export { getActivitiesIdQueryOptions } from "./hooks/useGetActivitiesId.ts";
export { useGetActivitiesId } from "./hooks/useGetActivitiesId.ts";
export { getActivitiesIdSuspenseQueryKey } from "./hooks/useGetActivitiesIdSuspense.ts";
export { getActivitiesIdSuspense } from "./hooks/useGetActivitiesIdSuspense.ts";
export { getActivitiesIdSuspenseQueryOptions } from "./hooks/useGetActivitiesIdSuspense.ts";
export { useGetActivitiesIdSuspense } from "./hooks/useGetActivitiesIdSuspense.ts";
export { getActivitiesSuspenseQueryKey } from "./hooks/useGetActivitiesSuspense.ts";
export { getActivitiesSuspense } from "./hooks/useGetActivitiesSuspense.ts";
export { getActivitiesSuspenseQueryOptions } from "./hooks/useGetActivitiesSuspense.ts";
export { useGetActivitiesSuspense } from "./hooks/useGetActivitiesSuspense.ts";
export { getJobRecommendationsQueryKey } from "./hooks/useGetJobRecommendations.ts";
export { getJobRecommendations } from "./hooks/useGetJobRecommendations.ts";
export { getJobRecommendationsQueryOptions } from "./hooks/useGetJobRecommendations.ts";
export { useGetJobRecommendations } from "./hooks/useGetJobRecommendations.ts";
export { getJobRecommendationsIdQueryKey } from "./hooks/useGetJobRecommendationsId.ts";
export { getJobRecommendationsId } from "./hooks/useGetJobRecommendationsId.ts";
export { getJobRecommendationsIdQueryOptions } from "./hooks/useGetJobRecommendationsId.ts";
export { useGetJobRecommendationsId } from "./hooks/useGetJobRecommendationsId.ts";
export { getJobRecommendationsIdSuspenseQueryKey } from "./hooks/useGetJobRecommendationsIdSuspense.ts";
export { getJobRecommendationsIdSuspense } from "./hooks/useGetJobRecommendationsIdSuspense.ts";
export { getJobRecommendationsIdSuspenseQueryOptions } from "./hooks/useGetJobRecommendationsIdSuspense.ts";
export { useGetJobRecommendationsIdSuspense } from "./hooks/useGetJobRecommendationsIdSuspense.ts";
export { getJobRecommendationsSuspenseQueryKey } from "./hooks/useGetJobRecommendationsSuspense.ts";
export { getJobRecommendationsSuspense } from "./hooks/useGetJobRecommendationsSuspense.ts";
export { getJobRecommendationsSuspenseQueryOptions } from "./hooks/useGetJobRecommendationsSuspense.ts";
export { useGetJobRecommendationsSuspense } from "./hooks/useGetJobRecommendationsSuspense.ts";
export { getMenusQueryKey } from "./hooks/useGetMenus.ts";
export { getMenus } from "./hooks/useGetMenus.ts";
export { getMenusQueryOptions } from "./hooks/useGetMenus.ts";
export { useGetMenus } from "./hooks/useGetMenus.ts";
export { getMenusIdQueryKey } from "./hooks/useGetMenusId.ts";
export { getMenusId } from "./hooks/useGetMenusId.ts";
export { getMenusIdQueryOptions } from "./hooks/useGetMenusId.ts";
export { useGetMenusId } from "./hooks/useGetMenusId.ts";
export { getMenusIdSuspenseQueryKey } from "./hooks/useGetMenusIdSuspense.ts";
export { getMenusIdSuspense } from "./hooks/useGetMenusIdSuspense.ts";
export { getMenusIdSuspenseQueryOptions } from "./hooks/useGetMenusIdSuspense.ts";
export { useGetMenusIdSuspense } from "./hooks/useGetMenusIdSuspense.ts";
export { getMenusSuspenseQueryKey } from "./hooks/useGetMenusSuspense.ts";
export { getMenusSuspense } from "./hooks/useGetMenusSuspense.ts";
export { getMenusSuspenseQueryOptions } from "./hooks/useGetMenusSuspense.ts";
export { useGetMenusSuspense } from "./hooks/useGetMenusSuspense.ts";
export { getProfileMeQueryKey } from "./hooks/useGetProfileMe.ts";
export { getProfileMe } from "./hooks/useGetProfileMe.ts";
export { getProfileMeQueryOptions } from "./hooks/useGetProfileMe.ts";
export { useGetProfileMe } from "./hooks/useGetProfileMe.ts";
export { getProfileMeSuspenseQueryKey } from "./hooks/useGetProfileMeSuspense.ts";
export { getProfileMeSuspense } from "./hooks/useGetProfileMeSuspense.ts";
export { getProfileMeSuspenseQueryOptions } from "./hooks/useGetProfileMeSuspense.ts";
export { useGetProfileMeSuspense } from "./hooks/useGetProfileMeSuspense.ts";
export { postActivitiesMutationKey } from "./hooks/usePostActivities.ts";
export { postActivities } from "./hooks/usePostActivities.ts";
export { postActivitiesMutationOptions } from "./hooks/usePostActivities.ts";
export { usePostActivities } from "./hooks/usePostActivities.ts";
export { postAuthLoginMutationKey } from "./hooks/usePostAuthLogin.ts";
export { postAuthLogin } from "./hooks/usePostAuthLogin.ts";
export { postAuthLoginMutationOptions } from "./hooks/usePostAuthLogin.ts";
export { usePostAuthLogin } from "./hooks/usePostAuthLogin.ts";
export { postAuthLoginVerifyMutationKey } from "./hooks/usePostAuthLoginVerify.ts";
export { postAuthLoginVerify } from "./hooks/usePostAuthLoginVerify.ts";
export { postAuthLoginVerifyMutationOptions } from "./hooks/usePostAuthLoginVerify.ts";
export { usePostAuthLoginVerify } from "./hooks/usePostAuthLoginVerify.ts";
export { postAuthRegisterMutationKey } from "./hooks/usePostAuthRegister.ts";
export { postAuthRegister } from "./hooks/usePostAuthRegister.ts";
export { postAuthRegisterMutationOptions } from "./hooks/usePostAuthRegister.ts";
export { usePostAuthRegister } from "./hooks/usePostAuthRegister.ts";
export { postAuthVerifyOtpMutationKey } from "./hooks/usePostAuthVerifyOtp.ts";
export { postAuthVerifyOtp } from "./hooks/usePostAuthVerifyOtp.ts";
export { postAuthVerifyOtpMutationOptions } from "./hooks/usePostAuthVerifyOtp.ts";
export { usePostAuthVerifyOtp } from "./hooks/usePostAuthVerifyOtp.ts";
export { postJobRecommendationsMutationKey } from "./hooks/usePostJobRecommendations.ts";
export { postJobRecommendations } from "./hooks/usePostJobRecommendations.ts";
export { postJobRecommendationsMutationOptions } from "./hooks/usePostJobRecommendations.ts";
export { usePostJobRecommendations } from "./hooks/usePostJobRecommendations.ts";
export { postMenusMutationKey } from "./hooks/usePostMenus.ts";
export { postMenus } from "./hooks/usePostMenus.ts";
export { postMenusMutationOptions } from "./hooks/usePostMenus.ts";
export { usePostMenus } from "./hooks/usePostMenus.ts";
export { putActivitiesIdMutationKey } from "./hooks/usePutActivitiesId.ts";
export { putActivitiesId } from "./hooks/usePutActivitiesId.ts";
export { putActivitiesIdMutationOptions } from "./hooks/usePutActivitiesId.ts";
export { usePutActivitiesId } from "./hooks/usePutActivitiesId.ts";
export { putJobRecommendationsIdMutationKey } from "./hooks/usePutJobRecommendationsId.ts";
export { putJobRecommendationsId } from "./hooks/usePutJobRecommendationsId.ts";
export { putJobRecommendationsIdMutationOptions } from "./hooks/usePutJobRecommendationsId.ts";
export { usePutJobRecommendationsId } from "./hooks/usePutJobRecommendationsId.ts";
export { putMenusIdMutationKey } from "./hooks/usePutMenusId.ts";
export { putMenusId } from "./hooks/usePutMenusId.ts";
export { putMenusIdMutationOptions } from "./hooks/usePutMenusId.ts";
export { usePutMenusId } from "./hooks/usePutMenusId.ts";
export { putProfileMeMutationKey } from "./hooks/usePutProfileMe.ts";
export { putProfileMe } from "./hooks/usePutProfileMe.ts";
export { putProfileMeMutationOptions } from "./hooks/usePutProfileMe.ts";
export { usePutProfileMe } from "./hooks/usePutProfileMe.ts";