/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteMenusIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Menu deleted
*/
export type DeleteMenusId204 = any;

export type DeleteMenusIdMutationResponse = DeleteMenusId204;

export type DeleteMenusIdMutation = {
    Response: DeleteMenusId204;
    PathParams: DeleteMenusIdPathParams;
    Errors: any;
};