/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteJobRecommendationsIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Job deleted
*/
export type DeleteJobRecommendationsId204 = any;

export type DeleteJobRecommendationsIdMutationResponse = DeleteJobRecommendationsId204;

export type DeleteJobRecommendationsIdMutation = {
    Response: DeleteJobRecommendationsId204;
    PathParams: DeleteJobRecommendationsIdPathParams;
    Errors: any;
};