/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteActivitiesIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Activity deleted
*/
export type DeleteActivitiesId204 = any;

export type DeleteActivitiesIdMutationResponse = DeleteActivitiesId204;

export type DeleteActivitiesIdMutation = {
    Response: DeleteActivitiesId204;
    PathParams: DeleteActivitiesIdPathParams;
    Errors: any;
};