/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetActivitiesIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Activity details
*/
export type GetActivitiesId200 = any;

/**
 * @description Activity not found
*/
export type GetActivitiesId404 = any;

export type GetActivitiesIdQueryResponse = GetActivitiesId200;

export type GetActivitiesIdQuery = {
    Response: GetActivitiesId200;
    PathParams: GetActivitiesIdPathParams;
    Errors: GetActivitiesId404;
};