/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description List of activities
*/
export type GetActivities200 = any;

export type GetActivitiesQueryResponse = GetActivities200;

export type GetActivitiesQuery = {
    Response: GetActivities200;
    Errors: any;
};