/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description List of job recommendations
*/
export type GetJobRecommendations200 = any;

export type GetJobRecommendationsQueryResponse = GetJobRecommendations200;

export type GetJobRecommendationsQuery = {
    Response: GetJobRecommendations200;
    Errors: any;
};