/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetJobRecommendationsIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Job details
*/
export type GetJobRecommendationsId200 = any;

/**
 * @description Job not found
*/
export type GetJobRecommendationsId404 = any;

export type GetJobRecommendationsIdQueryResponse = GetJobRecommendationsId200;

export type GetJobRecommendationsIdQuery = {
    Response: GetJobRecommendationsId200;
    PathParams: GetJobRecommendationsIdPathParams;
    Errors: GetJobRecommendationsId404;
};