/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description List of menus
*/
export type GetMenus200 = any;

export type GetMenusQueryResponse = GetMenus200;

export type GetMenusQuery = {
    Response: GetMenus200;
    Errors: any;
};