/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetMenusIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Menu details
*/
export type GetMenusId200 = any;

/**
 * @description Menu not found
*/
export type GetMenusId404 = any;

export type GetMenusIdQueryResponse = GetMenusId200;

export type GetMenusIdQuery = {
    Response: GetMenusId200;
    PathParams: GetMenusIdPathParams;
    Errors: GetMenusId404;
};