/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description User profile data
*/
export type GetProfileMe200 = {
    /**
     * @type integer | undefined
    */
    id?: number;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    firstName?: string;
    /**
     * @type string | undefined
    */
    lastName?: string;
    /**
     * @type string | undefined, date-time
    */
    dob?: string;
    /**
     * @type string | undefined
    */
    country?: string;
};

/**
 * @description Unauthorized
*/
export type GetProfileMe401 = any;

export type GetProfileMeQueryResponse = GetProfileMe200;

export type GetProfileMeQuery = {
    Response: GetProfileMe200;
    Errors: GetProfileMe401;
};