export type { DeleteActivitiesIdPathParams, DeleteActivitiesId204, DeleteActivitiesIdMutationResponse, DeleteActivitiesIdMutation } from "./DeleteActivitiesId.ts";
export type { DeleteJobRecommendationsIdPathParams, DeleteJobRecommendationsId204, DeleteJobRecommendationsIdMutationResponse, DeleteJobRecommendationsIdMutation } from "./DeleteJobRecommendationsId.ts";
export type { DeleteMenusIdPathParams, DeleteMenusId204, DeleteMenusIdMutationResponse, DeleteMenusIdMutation } from "./DeleteMenusId.ts";
export type { GetActivities200, GetActivitiesQueryResponse, GetActivitiesQuery } from "./GetActivities.ts";
export type { GetActivitiesIdPathParams, GetActivitiesId200, GetActivitiesId404, GetActivitiesIdQueryResponse, GetActivitiesIdQuery } from "./GetActivitiesId.ts";
export type { GetJobRecommendations200, GetJobRecommendationsQueryResponse, GetJobRecommendationsQuery } from "./GetJobRecommendations.ts";
export type { GetJobRecommendationsIdPathParams, GetJobRecommendationsId200, GetJobRecommendationsId404, GetJobRecommendationsIdQueryResponse, GetJobRecommendationsIdQuery } from "./GetJobRecommendationsId.ts";
export type { GetMenus200, GetMenusQueryResponse, GetMenusQuery } from "./GetMenus.ts";
export type { GetMenusIdPathParams, GetMenusId200, GetMenusId404, GetMenusIdQueryResponse, GetMenusIdQuery } from "./GetMenusId.ts";
export type { GetProfileMe200, GetProfileMe401, GetProfileMeQueryResponse, GetProfileMeQuery } from "./GetProfileMe.ts";
export type { PostActivities201, PostActivitiesMutationRequest, PostActivitiesMutationResponse, PostActivitiesMutation } from "./PostActivities.ts";
export type { PostAuthLogin200, PostAuthLogin401, PostAuthLoginMutationRequest, PostAuthLoginMutationResponse, PostAuthLoginMutation } from "./PostAuthLogin.ts";
export type { PostAuthLoginVerify200, PostAuthLoginVerify400, PostAuthLoginVerifyMutationRequest, PostAuthLoginVerifyMutationResponse, PostAuthLoginVerifyMutation } from "./PostAuthLoginVerify.ts";
export type { PostAuthRegister201, PostAuthRegister400, PostAuthRegisterMutationRequest, PostAuthRegisterMutationResponse, PostAuthRegisterMutation } from "./PostAuthRegister.ts";
export type { PostAuthVerifyOtp200, PostAuthVerifyOtp400, PostAuthVerifyOtpMutationRequest, PostAuthVerifyOtpMutationResponse, PostAuthVerifyOtpMutation } from "./PostAuthVerifyOtp.ts";
export type { PostJobRecommendations201, PostJobRecommendationsMutationRequest, PostJobRecommendationsMutationResponse, PostJobRecommendationsMutation } from "./PostJobRecommendations.ts";
export type { PostMenus201, PostMenusMutationRequest, PostMenusMutationResponse, PostMenusMutation } from "./PostMenus.ts";
export type { PutActivitiesIdPathParams, PutActivitiesId200, PutActivitiesIdMutationRequest, PutActivitiesIdMutationResponse, PutActivitiesIdMutation } from "./PutActivitiesId.ts";
export type { PutJobRecommendationsIdPathParams, PutJobRecommendationsId200, PutJobRecommendationsIdMutationRequest, PutJobRecommendationsIdMutationResponse, PutJobRecommendationsIdMutation } from "./PutJobRecommendationsId.ts";
export type { PutMenusIdPathParams, PutMenusId200, PutMenusIdMutationRequest, PutMenusIdMutationResponse, PutMenusIdMutation } from "./PutMenusId.ts";
export type { PutProfileMe200, PutProfileMe401, PutProfileMeMutationRequest, PutProfileMeMutationResponse, PutProfileMeMutation } from "./PutProfileMe.ts";