/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Login successful
*/
export type PostAuthLoginVerify200 = {
    /**
     * @type string | undefined
    */
    token?: string;
    /**
     * @type object | undefined
    */
    user?: object;
};

/**
 * @description Invalid or expired OTP
*/
export type PostAuthLoginVerify400 = any;

export type PostAuthLoginVerifyMutationRequest = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    otp: string;
};

export type PostAuthLoginVerifyMutationResponse = PostAuthLoginVerify200;

export type PostAuthLoginVerifyMutation = {
    Response: PostAuthLoginVerify200;
    Request: PostAuthLoginVerifyMutationRequest;
    Errors: PostAuthLoginVerify400;
};