/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Activity created
*/
export type PostActivities201 = any;

export type PostActivitiesMutationRequest = {
    /**
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    type?: string;
    /**
     * @type string, date-time
    */
    date: string;
};

export type PostActivitiesMutationResponse = PostActivities201;

export type PostActivitiesMutation = {
    Response: PostActivities201;
    Request: PostActivitiesMutationRequest;
    Errors: any;
};