/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Job created
*/
export type PostJobRecommendations201 = any;

export type PostJobRecommendationsMutationRequest = {
    /**
     * @type string
    */
    title: string;
    /**
     * @type string
    */
    company: string;
    /**
     * @type string | undefined
    */
    location?: string;
};

export type PostJobRecommendationsMutationResponse = PostJobRecommendations201;

export type PostJobRecommendationsMutation = {
    Response: PostJobRecommendations201;
    Request: PostJobRecommendationsMutationRequest;
    Errors: any;
};