/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Account activated successfully
*/
export type PostAuthVerifyOtp200 = any;

/**
 * @description Invalid OTP
*/
export type PostAuthVerifyOtp400 = any;

export type PostAuthVerifyOtpMutationRequest = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    otp: string;
};

export type PostAuthVerifyOtpMutationResponse = PostAuthVerifyOtp200;

export type PostAuthVerifyOtpMutation = {
    Response: PostAuthVerifyOtp200;
    Request: PostAuthVerifyOtpMutationRequest;
    Errors: PostAuthVerifyOtp400;
};