/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description OTP sent to email
*/
export type PostAuthLogin200 = any;

/**
 * @description Invalid credentials
*/
export type PostAuthLogin401 = any;

export type PostAuthLoginMutationRequest = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    password: string;
};

export type PostAuthLoginMutationResponse = PostAuthLogin200;

export type PostAuthLoginMutation = {
    Response: PostAuthLogin200;
    Request: PostAuthLoginMutationRequest;
    Errors: PostAuthLogin401;
};