/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description User registered successfully
*/
export type PostAuthRegister201 = any;

/**
 * @description Bad request
*/
export type PostAuthRegister400 = any;

export type PostAuthRegisterMutationRequest = {
    /**
     * @type string
    */
    firstName: string;
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    password: string;
};

export type PostAuthRegisterMutationResponse = PostAuthRegister201;

export type PostAuthRegisterMutation = {
    Response: PostAuthRegister201;
    Request: PostAuthRegisterMutationRequest;
    Errors: PostAuthRegister400;
};