/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Menu created
*/
export type PostMenus201 = any;

export type PostMenusMutationRequest = {
    /**
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    icon?: string;
    /**
     * @type string | undefined
    */
    link?: string;
};

export type PostMenusMutationResponse = PostMenus201;

export type PostMenusMutation = {
    Response: PostMenus201;
    Request: PostMenusMutationRequest;
    Errors: any;
};