/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutActivitiesIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Activity updated
*/
export type PutActivitiesId200 = any;

export type PutActivitiesIdMutationRequest = {
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    type?: string;
    /**
     * @type string | undefined, date-time
    */
    date?: string;
};

export type PutActivitiesIdMutationResponse = PutActivitiesId200;

export type PutActivitiesIdMutation = {
    Response: PutActivitiesId200;
    Request: PutActivitiesIdMutationRequest;
    PathParams: PutActivitiesIdPathParams;
    Errors: any;
};