/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutJobRecommendationsIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Job updated
*/
export type PutJobRecommendationsId200 = any;

export type PutJobRecommendationsIdMutationRequest = {
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    company?: string;
    /**
     * @type string | undefined
    */
    location?: string;
};

export type PutJobRecommendationsIdMutationResponse = PutJobRecommendationsId200;

export type PutJobRecommendationsIdMutation = {
    Response: PutJobRecommendationsId200;
    Request: PutJobRecommendationsIdMutationRequest;
    PathParams: PutJobRecommendationsIdPathParams;
    Errors: any;
};