/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PutMenusIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description Menu updated
*/
export type PutMenusId200 = any;

export type PutMenusIdMutationRequest = {
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    icon?: string;
    /**
     * @type string | undefined
    */
    link?: string;
};

export type PutMenusIdMutationResponse = PutMenusId200;

export type PutMenusIdMutation = {
    Response: PutMenusId200;
    Request: PutMenusIdMutationRequest;
    PathParams: PutMenusIdPathParams;
    Errors: any;
};