/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Profile updated successfully
*/
export type PutProfileMe200 = any;

/**
 * @description Unauthorized
*/
export type PutProfileMe401 = any;

export type PutProfileMeMutationRequest = {
    /**
     * @type string | undefined
    */
    firstName?: string;
    /**
     * @type string | undefined
    */
    lastName?: string;
    /**
     * @type string | undefined, date
    */
    dob?: string;
    /**
     * @type string | undefined
    */
    country?: string;
};

export type PutProfileMeMutationResponse = PutProfileMe200;

export type PutProfileMeMutation = {
    Response: PutProfileMe200;
    Request: PutProfileMeMutationRequest;
    Errors: PutProfileMe401;
};