/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthVerifyResetPasswordQueryResponse, GetApiAuthVerifyResetPasswordQueryParams } from "../types/GetApiAuthVerifyResetPassword.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiAuthVerifyResetPasswordSuspenseQueryKey = (params: GetApiAuthVerifyResetPasswordQueryParams) => [{ url: '/api/auth/verify-reset-password' }, ...(params ? [params] : [])] as const

export type GetApiAuthVerifyResetPasswordSuspenseQueryKey = ReturnType<typeof getApiAuthVerifyResetPasswordSuspenseQueryKey>

/**
 * {@link /api/auth/verify-reset-password}
 */
export async function getApiAuthVerifyResetPasswordSuspense(params: GetApiAuthVerifyResetPasswordQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiAuthVerifyResetPasswordQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/auth/verify-reset-password`, params, ... requestConfig })  
  return res
}

export function getApiAuthVerifyResetPasswordSuspenseQueryOptions(params: GetApiAuthVerifyResetPasswordQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiAuthVerifyResetPasswordSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthVerifyResetPasswordSuspense(params, config)
   },
  })
}

/**
 * {@link /api/auth/verify-reset-password}
 */
export function useGetApiAuthVerifyResetPasswordSuspense<TData = ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, TQueryKey extends QueryKey = GetApiAuthVerifyResetPasswordSuspenseQueryKey>(params: GetApiAuthVerifyResetPasswordQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiAuthVerifyResetPasswordSuspenseQueryKey(params)


  const query = useSuspenseQuery({
   ...getApiAuthVerifyResetPasswordSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}