/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiTaskManagerIdQueryResponse, GetApiTaskManagerIdPathParams } from "../types/GetApiTaskManagerId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiTaskManagerIdQueryKey = (Id: GetApiTaskManagerIdPathParams["Id"]) => [{ url: '/api/task-manager/:Id', params: {Id:Id} }] as const

export type GetApiTaskManagerIdQueryKey = ReturnType<typeof getApiTaskManagerIdQueryKey>

/**
 * {@link /api/task-manager/:Id}
 */
export async function getApiTaskManagerId(Id: GetApiTaskManagerIdPathParams["Id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiTaskManagerIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-manager/${Id}`, ... requestConfig })  
  return res
}

export function getApiTaskManagerIdQueryOptions(Id: GetApiTaskManagerIdPathParams["Id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiTaskManagerIdQueryKey(Id)
  return queryOptions<ResponseConfig<GetApiTaskManagerIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiTaskManagerIdQueryResponse>, typeof queryKey>({
   enabled: !!(Id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTaskManagerId(Id, config)
   },
  })
}

/**
 * {@link /api/task-manager/:Id}
 */
export function useGetApiTaskManagerId<TData = ResponseConfig<GetApiTaskManagerIdQueryResponse>, TQueryData = ResponseConfig<GetApiTaskManagerIdQueryResponse>, TQueryKey extends QueryKey = GetApiTaskManagerIdQueryKey>(Id: GetApiTaskManagerIdPathParams["Id"], options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetApiTaskManagerIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiTaskManagerIdQueryKey(Id)


  const query = useQuery({
   ...getApiTaskManagerIdQueryOptions(Id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}