/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthMeQueryResponse } from "../types/GetApiAuthMe.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiAuthMeSuspenseQueryKey = () => [{ url: '/api/auth/me' }] as const

export type GetApiAuthMeSuspenseQueryKey = ReturnType<typeof getApiAuthMeSuspenseQueryKey>

/**
 * {@link /api/auth/me}
 */
export async function getApiAuthMeSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiAuthMeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/auth/me`, ... requestConfig })  
  return res
}

export function getApiAuthMeSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiAuthMeSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetApiAuthMeQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiAuthMeQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthMeSuspense(config)
   },
  })
}

/**
 * {@link /api/auth/me}
 */
export function useGetApiAuthMeSuspense<TData = ResponseConfig<GetApiAuthMeQueryResponse>, TQueryKey extends QueryKey = GetApiAuthMeSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiAuthMeQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiAuthMeSuspenseQueryKey()


  const query = useSuspenseQuery({
   ...getApiAuthMeSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}