/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiTaskManagerIdQueryResponse, GetApiTaskManagerIdPathParams } from "../types/GetApiTaskManagerId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiTaskManagerIdSuspenseQueryKey = (Id: GetApiTaskManagerIdPathParams["Id"]) => [{ url: '/api/task-manager/:Id', params: {Id:Id} }] as const

export type GetApiTaskManagerIdSuspenseQueryKey = ReturnType<typeof getApiTaskManagerIdSuspenseQueryKey>

/**
 * {@link /api/task-manager/:Id}
 */
export async function getApiTaskManagerIdSuspense(Id: GetApiTaskManagerIdPathParams["Id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiTaskManagerIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-manager/${Id}`, ... requestConfig })  
  return res
}

export function getApiTaskManagerIdSuspenseQueryOptions(Id: GetApiTaskManagerIdPathParams["Id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiTaskManagerIdSuspenseQueryKey(Id)
  return queryOptions<ResponseConfig<GetApiTaskManagerIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiTaskManagerIdQueryResponse>, typeof queryKey>({
   enabled: !!(Id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTaskManagerIdSuspense(Id, config)
   },
  })
}

/**
 * {@link /api/task-manager/:Id}
 */
export function useGetApiTaskManagerIdSuspense<TData = ResponseConfig<GetApiTaskManagerIdQueryResponse>, TQueryKey extends QueryKey = GetApiTaskManagerIdSuspenseQueryKey>(Id: GetApiTaskManagerIdPathParams["Id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiTaskManagerIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiTaskManagerIdSuspenseQueryKey(Id)


  const query = useSuspenseQuery({
   ...getApiTaskManagerIdSuspenseQueryOptions(Id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}