/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthMeQueryResponse } from "../types/GetApiAuthMe.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiAuthMeQueryKey = () => [{ url: '/api/auth/me' }] as const

export type GetApiAuthMeQueryKey = ReturnType<typeof getApiAuthMeQueryKey>

/**
 * {@link /api/auth/me}
 */
export async function getApiAuthMe(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiAuthMeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/auth/me`, ... requestConfig })  
  return res
}

export function getApiAuthMeQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiAuthMeQueryKey()
  return queryOptions<ResponseConfig<GetApiAuthMeQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiAuthMeQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthMe(config)
   },
  })
}

/**
 * {@link /api/auth/me}
 */
export function useGetApiAuthMe<TData = ResponseConfig<GetApiAuthMeQueryResponse>, TQueryData = ResponseConfig<GetApiAuthMeQueryResponse>, TQueryKey extends QueryKey = GetApiAuthMeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetApiAuthMeQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiAuthMeQueryKey()


  const query = useQuery({
   ...getApiAuthMeQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}