/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiTaskManagerQueryResponse, GetApiTaskManagerQueryParams } from "../types/GetApiTaskManager.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiTaskManagerSuspenseQueryKey = (params: GetApiTaskManagerQueryParams = {}) => [{ url: '/api/task-manager' }, ...(params ? [params] : [])] as const

export type GetApiTaskManagerSuspenseQueryKey = ReturnType<typeof getApiTaskManagerSuspenseQueryKey>

/**
 * {@link /api/task-manager}
 */
export async function getApiTaskManagerSuspense(params?: GetApiTaskManagerQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiTaskManagerQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-manager`, params, ... requestConfig })  
  return res
}

export function getApiTaskManagerSuspenseQueryOptions(params?: GetApiTaskManagerQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiTaskManagerSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<GetApiTaskManagerQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiTaskManagerQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTaskManagerSuspense(params, config)
   },
  })
}

/**
 * {@link /api/task-manager}
 */
export function useGetApiTaskManagerSuspense<TData = ResponseConfig<GetApiTaskManagerQueryResponse>, TQueryKey extends QueryKey = GetApiTaskManagerSuspenseQueryKey>(params?: GetApiTaskManagerQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiTaskManagerQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiTaskManagerSuspenseQueryKey(params)


  const query = useSuspenseQuery({
   ...getApiTaskManagerSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}