/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiTaskManagerQueryResponse, GetApiTaskManagerQueryParams } from "../types/GetApiTaskManager.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiTaskManagerQueryKey = (params: GetApiTaskManagerQueryParams = {}) => [{ url: '/api/task-manager' }, ...(params ? [params] : [])] as const

export type GetApiTaskManagerQueryKey = ReturnType<typeof getApiTaskManagerQueryKey>

/**
 * {@link /api/task-manager}
 */
export async function getApiTaskManager(params?: GetApiTaskManagerQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiTaskManagerQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-manager`, params, ... requestConfig })  
  return res
}

export function getApiTaskManagerQueryOptions(params?: GetApiTaskManagerQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiTaskManagerQueryKey(params)
  return queryOptions<ResponseConfig<GetApiTaskManagerQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiTaskManagerQueryResponse>, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTaskManager(params, config)
   },
  })
}

/**
 * {@link /api/task-manager}
 */
export function useGetApiTaskManager<TData = ResponseConfig<GetApiTaskManagerQueryResponse>, TQueryData = ResponseConfig<GetApiTaskManagerQueryResponse>, TQueryKey extends QueryKey = GetApiTaskManagerQueryKey>(params?: GetApiTaskManagerQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetApiTaskManagerQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiTaskManagerQueryKey(params)


  const query = useQuery({
   ...getApiTaskManagerQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}