/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthVerifyAccountActivationQueryResponse, GetApiAuthVerifyAccountActivationQueryParams } from "../types/GetApiAuthVerifyAccountActivation.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiAuthVerifyAccountActivationQueryKey = (params: GetApiAuthVerifyAccountActivationQueryParams) => [{ url: '/api/auth/verify-account-activation' }, ...(params ? [params] : [])] as const

export type GetApiAuthVerifyAccountActivationQueryKey = ReturnType<typeof getApiAuthVerifyAccountActivationQueryKey>

/**
 * {@link /api/auth/verify-account-activation}
 */
export async function getApiAuthVerifyAccountActivation(params: GetApiAuthVerifyAccountActivationQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiAuthVerifyAccountActivationQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/auth/verify-account-activation`, params, ... requestConfig })  
  return res
}

export function getApiAuthVerifyAccountActivationQueryOptions(params: GetApiAuthVerifyAccountActivationQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiAuthVerifyAccountActivationQueryKey(params)
  return queryOptions<ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthVerifyAccountActivation(params, config)
   },
  })
}

/**
 * {@link /api/auth/verify-account-activation}
 */
export function useGetApiAuthVerifyAccountActivation<TData = ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, TQueryData = ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, TQueryKey extends QueryKey = GetApiAuthVerifyAccountActivationQueryKey>(params: GetApiAuthVerifyAccountActivationQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiAuthVerifyAccountActivationQueryKey(params)


  const query = useQuery({
   ...getApiAuthVerifyAccountActivationQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}