/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthVerifyResetPasswordQueryResponse, GetApiAuthVerifyResetPasswordQueryParams } from "../types/GetApiAuthVerifyResetPassword.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiAuthVerifyResetPasswordQueryKey = (params: GetApiAuthVerifyResetPasswordQueryParams) => [{ url: '/api/auth/verify-reset-password' }, ...(params ? [params] : [])] as const

export type GetApiAuthVerifyResetPasswordQueryKey = ReturnType<typeof getApiAuthVerifyResetPasswordQueryKey>

/**
 * {@link /api/auth/verify-reset-password}
 */
export async function getApiAuthVerifyResetPassword(params: GetApiAuthVerifyResetPasswordQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiAuthVerifyResetPasswordQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/auth/verify-reset-password`, params, ... requestConfig })  
  return res
}

export function getApiAuthVerifyResetPasswordQueryOptions(params: GetApiAuthVerifyResetPasswordQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiAuthVerifyResetPasswordQueryKey(params)
  return queryOptions<ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthVerifyResetPassword(params, config)
   },
  })
}

/**
 * {@link /api/auth/verify-reset-password}
 */
export function useGetApiAuthVerifyResetPassword<TData = ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, TQueryData = ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, TQueryKey extends QueryKey = GetApiAuthVerifyResetPasswordQueryKey>(params: GetApiAuthVerifyResetPasswordQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ResponseConfig<GetApiAuthVerifyResetPasswordQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiAuthVerifyResetPasswordQueryKey(params)


  const query = useQuery({
   ...getApiAuthVerifyResetPasswordQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}