/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthVerifyAccountActivationQueryResponse, GetApiAuthVerifyAccountActivationQueryParams } from "../types/GetApiAuthVerifyAccountActivation.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiAuthVerifyAccountActivationSuspenseQueryKey = (params: GetApiAuthVerifyAccountActivationQueryParams) => [{ url: '/api/auth/verify-account-activation' }, ...(params ? [params] : [])] as const

export type GetApiAuthVerifyAccountActivationSuspenseQueryKey = ReturnType<typeof getApiAuthVerifyAccountActivationSuspenseQueryKey>

/**
 * {@link /api/auth/verify-account-activation}
 */
export async function getApiAuthVerifyAccountActivationSuspense(params: GetApiAuthVerifyAccountActivationQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiAuthVerifyAccountActivationQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/auth/verify-account-activation`, params, ... requestConfig })  
  return res
}

export function getApiAuthVerifyAccountActivationSuspenseQueryOptions(params: GetApiAuthVerifyAccountActivationQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getApiAuthVerifyAccountActivationSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthVerifyAccountActivationSuspense(params, config)
   },
  })
}

/**
 * {@link /api/auth/verify-account-activation}
 */
export function useGetApiAuthVerifyAccountActivationSuspense<TData = ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, TQueryKey extends QueryKey = GetApiAuthVerifyAccountActivationSuspenseQueryKey>(params: GetApiAuthVerifyAccountActivationQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiAuthVerifyAccountActivationQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getApiAuthVerifyAccountActivationSuspenseQueryKey(params)


  const query = useSuspenseQuery({
   ...getApiAuthVerifyAccountActivationSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}