/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthGoogleMutationRequest, PostApiAuthGoogleMutationResponse } from "../types/PostApiAuthGoogle.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthGoogleMutationKey = () => [{ url: '/api/auth/google' }] as const

export type PostApiAuthGoogleMutationKey = ReturnType<typeof postApiAuthGoogleMutationKey>

/**
 * {@link /api/auth/google}
 */
export async function postApiAuthGoogle(data?: PostApiAuthGoogleMutationRequest, config: Partial<RequestConfig<PostApiAuthGoogleMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthGoogleMutationResponse, ResponseErrorConfig<Error>, PostApiAuthGoogleMutationRequest>({ method : "POST", url : `/api/auth/google`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthGoogleMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthGoogleMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthGoogleMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthGoogleMutationResponse>, ResponseErrorConfig<Error>, {data?: PostApiAuthGoogleMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthGoogle(data, config)
    },
  })
}

/**
 * {@link /api/auth/google}
 */
export function usePostApiAuthGoogle<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthGoogleMutationResponse>, ResponseErrorConfig<Error>, {data?: PostApiAuthGoogleMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthGoogleMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthGoogleMutationKey()

  const baseOptions = postApiAuthGoogleMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthGoogleMutationResponse>, ResponseErrorConfig<Error>, {data?: PostApiAuthGoogleMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthGoogleMutationResponse>, ResponseErrorConfig<Error>, {data?: PostApiAuthGoogleMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthGoogleMutationResponse>, ResponseErrorConfig<Error>, {data?: PostApiAuthGoogleMutationRequest}, TContext>
}