/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthLogoutMutationRequest, PostApiAuthLogoutMutationResponse } from "../types/PostApiAuthLogout.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthLogoutMutationKey = () => [{ url: '/api/auth/logout' }] as const

export type PostApiAuthLogoutMutationKey = ReturnType<typeof postApiAuthLogoutMutationKey>

/**
 * {@link /api/auth/logout}
 */
export async function postApiAuthLogout(data: PostApiAuthLogoutMutationRequest, config: Partial<RequestConfig<PostApiAuthLogoutMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthLogoutMutationResponse, ResponseErrorConfig<Error>, PostApiAuthLogoutMutationRequest>({ method : "POST", url : `/api/auth/logout`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthLogoutMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthLogoutMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthLogoutMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthLogoutMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLogoutMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthLogout(data, config)
    },
  })
}

/**
 * {@link /api/auth/logout}
 */
export function usePostApiAuthLogout<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthLogoutMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLogoutMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthLogoutMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthLogoutMutationKey()

  const baseOptions = postApiAuthLogoutMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthLogoutMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLogoutMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthLogoutMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLogoutMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthLogoutMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLogoutMutationRequest}, TContext>
}