/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthRegisterMutationRequest, PostApiAuthRegisterMutationResponse } from "../types/PostApiAuthRegister.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthRegisterMutationKey = () => [{ url: '/api/auth/register' }] as const

export type PostApiAuthRegisterMutationKey = ReturnType<typeof postApiAuthRegisterMutationKey>

/**
 * {@link /api/auth/register}
 */
export async function postApiAuthRegister(data: PostApiAuthRegisterMutationRequest, config: Partial<RequestConfig<PostApiAuthRegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthRegisterMutationResponse, ResponseErrorConfig<Error>, PostApiAuthRegisterMutationRequest>({ method : "POST", url : `/api/auth/register`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthRegisterMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthRegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthRegisterMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthRegisterMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRegisterMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthRegister(data, config)
    },
  })
}

/**
 * {@link /api/auth/register}
 */
export function usePostApiAuthRegister<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthRegisterMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRegisterMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthRegisterMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthRegisterMutationKey()

  const baseOptions = postApiAuthRegisterMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthRegisterMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRegisterMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthRegisterMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRegisterMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthRegisterMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRegisterMutationRequest}, TContext>
}