/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthRefreshMutationRequest, PostApiAuthRefreshMutationResponse } from "../types/PostApiAuthRefresh.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthRefreshMutationKey = () => [{ url: '/api/auth/refresh' }] as const

export type PostApiAuthRefreshMutationKey = ReturnType<typeof postApiAuthRefreshMutationKey>

/**
 * {@link /api/auth/refresh}
 */
export async function postApiAuthRefresh(data: PostApiAuthRefreshMutationRequest, config: Partial<RequestConfig<PostApiAuthRefreshMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthRefreshMutationResponse, ResponseErrorConfig<Error>, PostApiAuthRefreshMutationRequest>({ method : "POST", url : `/api/auth/refresh`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthRefreshMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthRefreshMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthRefreshMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthRefreshMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRefreshMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthRefresh(data, config)
    },
  })
}

/**
 * {@link /api/auth/refresh}
 */
export function usePostApiAuthRefresh<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthRefreshMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRefreshMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthRefreshMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthRefreshMutationKey()

  const baseOptions = postApiAuthRefreshMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthRefreshMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRefreshMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthRefreshMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRefreshMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthRefreshMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthRefreshMutationRequest}, TContext>
}