/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthLoginMutationRequest, PostApiAuthLoginMutationResponse } from "../types/PostApiAuthLogin.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthLoginMutationKey = () => [{ url: '/api/auth/login' }] as const

export type PostApiAuthLoginMutationKey = ReturnType<typeof postApiAuthLoginMutationKey>

/**
 * {@link /api/auth/login}
 */
export async function postApiAuthLogin(data: PostApiAuthLoginMutationRequest, config: Partial<RequestConfig<PostApiAuthLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthLoginMutationResponse, ResponseErrorConfig<Error>, PostApiAuthLoginMutationRequest>({ method : "POST", url : `/api/auth/login`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthLoginMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthLoginMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthLoginMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLoginMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthLogin(data, config)
    },
  })
}

/**
 * {@link /api/auth/login}
 */
export function usePostApiAuthLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthLoginMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthLoginMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthLoginMutationKey()

  const baseOptions = postApiAuthLoginMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthLoginMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLoginMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthLoginMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLoginMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthLoginMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthLoginMutationRequest}, TContext>
}