/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthForgetPasswordMutationRequest, PostApiAuthForgetPasswordMutationResponse } from "../types/PostApiAuthForgetPassword.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthForgetPasswordMutationKey = () => [{ url: '/api/auth/forget-password' }] as const

export type PostApiAuthForgetPasswordMutationKey = ReturnType<typeof postApiAuthForgetPasswordMutationKey>

/**
 * {@link /api/auth/forget-password}
 */
export async function postApiAuthForgetPassword(data: PostApiAuthForgetPasswordMutationRequest, config: Partial<RequestConfig<PostApiAuthForgetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthForgetPasswordMutationResponse, ResponseErrorConfig<Error>, PostApiAuthForgetPasswordMutationRequest>({ method : "POST", url : `/api/auth/forget-password`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthForgetPasswordMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthForgetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthForgetPasswordMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthForgetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthForgetPasswordMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthForgetPassword(data, config)
    },
  })
}

/**
 * {@link /api/auth/forget-password}
 */
export function usePostApiAuthForgetPassword<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthForgetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthForgetPasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthForgetPasswordMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthForgetPasswordMutationKey()

  const baseOptions = postApiAuthForgetPasswordMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthForgetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthForgetPasswordMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthForgetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthForgetPasswordMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthForgetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthForgetPasswordMutationRequest}, TContext>
}