/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthResetPasswordMutationRequest, PostApiAuthResetPasswordMutationResponse } from "../types/PostApiAuthResetPassword.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthResetPasswordMutationKey = () => [{ url: '/api/auth/reset-password' }] as const

export type PostApiAuthResetPasswordMutationKey = ReturnType<typeof postApiAuthResetPasswordMutationKey>

/**
 * {@link /api/auth/reset-password}
 */
export async function postApiAuthResetPassword(data: PostApiAuthResetPasswordMutationRequest, config: Partial<RequestConfig<PostApiAuthResetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthResetPasswordMutationResponse, ResponseErrorConfig<Error>, PostApiAuthResetPasswordMutationRequest>({ method : "POST", url : `/api/auth/reset-password`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthResetPasswordMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthResetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthResetPasswordMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthResetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthResetPasswordMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthResetPassword(data, config)
    },
  })
}

/**
 * {@link /api/auth/reset-password}
 */
export function usePostApiAuthResetPassword<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthResetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthResetPasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthResetPasswordMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthResetPasswordMutationKey()

  const baseOptions = postApiAuthResetPasswordMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthResetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthResetPasswordMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthResetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthResetPasswordMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthResetPasswordMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthResetPasswordMutationRequest}, TContext>
}