/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PutApiAuthUpdateProfileMutationRequest, PutApiAuthUpdateProfileMutationResponse } from "../types/PutApiAuthUpdateProfile.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { buildFormData } from "../.kubb/config.ts";

export const putApiAuthUpdateProfileMutationKey = () => [{ url: '/api/auth/update-profile' }] as const

export type PutApiAuthUpdateProfileMutationKey = ReturnType<typeof putApiAuthUpdateProfileMutationKey>

/**
 * {@link /api/auth/update-profile}
 */
export async function putApiAuthUpdateProfile(data?: PutApiAuthUpdateProfileMutationRequest, config: Partial<RequestConfig<PutApiAuthUpdateProfileMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  const formData = buildFormData(requestData)  
  const res = await request<PutApiAuthUpdateProfileMutationResponse, ResponseErrorConfig<Error>, PutApiAuthUpdateProfileMutationRequest>({ method : "PUT", url : `/api/auth/update-profile`, data : formData as FormData, ... requestConfig })  
  return res
}

export function putApiAuthUpdateProfileMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutApiAuthUpdateProfileMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putApiAuthUpdateProfileMutationKey()
  return mutationOptions<ResponseConfig<PutApiAuthUpdateProfileMutationResponse>, ResponseErrorConfig<Error>, {data?: PutApiAuthUpdateProfileMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return putApiAuthUpdateProfile(data, config)
    },
  })
}

/**
 * {@link /api/auth/update-profile}
 */
export function usePutApiAuthUpdateProfile<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PutApiAuthUpdateProfileMutationResponse>, ResponseErrorConfig<Error>, {data?: PutApiAuthUpdateProfileMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutApiAuthUpdateProfileMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putApiAuthUpdateProfileMutationKey()

  const baseOptions = putApiAuthUpdateProfileMutationOptions(config) as UseMutationOptions<ResponseConfig<PutApiAuthUpdateProfileMutationResponse>, ResponseErrorConfig<Error>, {data?: PutApiAuthUpdateProfileMutationRequest}, TContext>


  return useMutation<ResponseConfig<PutApiAuthUpdateProfileMutationResponse>, ResponseErrorConfig<Error>, {data?: PutApiAuthUpdateProfileMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PutApiAuthUpdateProfileMutationResponse>, ResponseErrorConfig<Error>, {data?: PutApiAuthUpdateProfileMutationRequest}, TContext>
}