/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthAccountActivationMutationRequest, PostApiAuthAccountActivationMutationResponse } from "../types/PostApiAuthAccountActivation.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiAuthAccountActivationMutationKey = () => [{ url: '/api/auth/account-activation' }] as const

export type PostApiAuthAccountActivationMutationKey = ReturnType<typeof postApiAuthAccountActivationMutationKey>

/**
 * {@link /api/auth/account-activation}
 */
export async function postApiAuthAccountActivation(data: PostApiAuthAccountActivationMutationRequest, config: Partial<RequestConfig<PostApiAuthAccountActivationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiAuthAccountActivationMutationResponse, ResponseErrorConfig<Error>, PostApiAuthAccountActivationMutationRequest>({ method : "POST", url : `/api/auth/account-activation`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiAuthAccountActivationMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiAuthAccountActivationMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiAuthAccountActivationMutationKey()
  return mutationOptions<ResponseConfig<PostApiAuthAccountActivationMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthAccountActivationMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiAuthAccountActivation(data, config)
    },
  })
}

/**
 * {@link /api/auth/account-activation}
 */
export function usePostApiAuthAccountActivation<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiAuthAccountActivationMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthAccountActivationMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiAuthAccountActivationMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthAccountActivationMutationKey()

  const baseOptions = postApiAuthAccountActivationMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiAuthAccountActivationMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthAccountActivationMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiAuthAccountActivationMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthAccountActivationMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiAuthAccountActivationMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiAuthAccountActivationMutationRequest}, TContext>
}