/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/infrastructure/http/axios-client.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/infrastructure/http/axios-client.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiTaskManagerMutationRequest, PostApiTaskManagerMutationResponse } from "../types/PostApiTaskManager.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiTaskManagerMutationKey = () => [{ url: '/api/task-manager' }] as const

export type PostApiTaskManagerMutationKey = ReturnType<typeof postApiTaskManagerMutationKey>

/**
 * {@link /api/task-manager}
 */
export async function postApiTaskManager(data: PostApiTaskManagerMutationRequest, config: Partial<RequestConfig<PostApiTaskManagerMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostApiTaskManagerMutationResponse, ResponseErrorConfig<Error>, PostApiTaskManagerMutationRequest>({ method : "POST", url : `/api/task-manager`, data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })  
  return res
}

export function postApiTaskManagerMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiTaskManagerMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postApiTaskManagerMutationKey()
  return mutationOptions<ResponseConfig<PostApiTaskManagerMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiTaskManagerMutationRequest}, TContext>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postApiTaskManager(data, config)
    },
  })
}

/**
 * {@link /api/task-manager}
 */
export function usePostApiTaskManager<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<PostApiTaskManagerMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiTaskManagerMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiTaskManagerMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postApiTaskManagerMutationKey()

  const baseOptions = postApiTaskManagerMutationOptions(config) as UseMutationOptions<ResponseConfig<PostApiTaskManagerMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiTaskManagerMutationRequest}, TContext>


  return useMutation<ResponseConfig<PostApiTaskManagerMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiTaskManagerMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<PostApiTaskManagerMutationResponse>, ResponseErrorConfig<Error>, {data: PostApiTaskManagerMutationRequest}, TContext>
}